/* This file generated by /home0/cborntra/REPOS/ATLAS/build/..//tune/blas/gemm/txover.c
 */
#ifndef ATL_TXOVER_H
   #define ATL_TXOVER_H 1

   #define ATL_PDIM 3
static const int ATL_tmmNN_SQmnk_XO[3] = 
   {163,163,324};
static const int ATL_tmmNT_SQmnk_XO[3] = 
   {163,163,324};
static const int ATL_tmmTN_SQmnk_XO[3] = 
   {163,163,324};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
 ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[27] = 
   {0,2896,0,0,2896,0,0,1057,0,308,535,2961,308,340,1966,172,322,814,172,321,650,172,327,646,0,80,0};
static const int ATL_tmmNT_SmnLk_XO[27] = 
   {0,0,0,0,0,0,1269,1269,3785,0,565,2047,324,394,1127,170,367,917,170,334,648,170,323,707,0,80,0};
static const int ATL_tmmTN_SmnLk_XO[27] = 
   {0,5854,0,0,4838,0,1871,1916,0,498,675,3160,321,331,1629,172,324,660,172,320,649,172,327,646,0,80,5907};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
 ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[27] = 
   {1872,1872,0,0,1616,5664,635,705,2897,635,647,2698,291,331,0,172,320,649,172,320,649,172,327,646,80,170,322};
static const int ATL_tmmNT_SmkLn_XO[27] = 
   {1895,2855,0,1320,1342,0,654,692,3055,616,1044,3231,285,338,1241,172,321,706,172,320,649,172,327,646,80,170,322};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
 ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[27] = 
   {0,0,0,2253,4053,0,0,1550,0,823,943,5377,310,374,2539,172,320,649,172,320,649,172,327,646,80,170,322};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[27] = 
   {3869,5388,0,1650,2877,0,1242,1733,5750,687,1192,3337,321,515,2175,172,321,1651,172,320,649,172,327,646,80,170,322};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
 ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[27] = 
   {0,321,650,172,336,650,172,321,650,172,321,650,172,321,650,172,321,650,172,321,650,172,327,646,80,171,325};
static const int ATL_tmmNT_SmLnk_XO[27] = 
   {172,321,650,172,321,650,172,321,650,172,321,650,172,321,650,172,321,650,172,321,650,172,327,646,80,171,325};
static const int ATL_tmmTN_SmLnk_XO[27] = 
   {172,321,650,172,321,650,172,321,650,172,321,650,172,321,650,172,321,650,172,321,650,172,327,646,80,171,325};
static const int ATL_tmmTT_SmLnk_XO[27] = 
   {173,322,651,173,322,651,173,322,651,173,326,665,173,322,651,173,322,651,173,322,651,173,322,650,85,171,325};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
 ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[27] = 
   {181,325,643,181,322,2209,181,434,1194,181,321,650,172,321,650,172,321,650,172,321,650,172,327,646,80,171,325};
static const int ATL_tmmNT_SnLmk_XO[27] = 
   {172,321,650,172,425,650,172,321,650,172,321,650,172,321,650,172,321,650,172,321,650,172,327,646,80,171,325};
static const int ATL_tmmTN_SnLmk_XO[27] = 
   {172,325,784,172,321,650,172,321,650,172,321,650,172,321,650,172,321,650,172,321,650,172,327,646,80,171,325};
static const int ATL_tmmTT_SnLmk_XO[27] = 
   {0,329,658,181,321,650,172,321,650,172,321,650,172,321,650,172,321,650,172,321,650,172,327,646,80,171,325};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
 ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[27] = 
   {0,171,335,0,171,320,0,171,320,0,171,320,0,171,320,0,171,320,0,171,320,171,171,325,80,171,325};
static const int ATL_tmmNT_SkLmn_XO[27] = 
   {0,162,656,0,162,326,0,162,416,0,162,326,0,162,326,0,162,326,0,162,326,162,174,585,80,171,325};
static const int ATL_tmmTN_SkLmn_XO[27] = 
   {0,171,335,0,171,320,0,171,320,0,171,320,0,171,663,0,171,320,0,171,320,171,171,325,80,171,325};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
 ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
