#!/bin/sh
if [ ! -f "Make.inc" ]
then
   echo "This routine expects a Make.inc from an ATLAS install!"
   exit 1
fi
blddir=`pwd`
path=`echo $0 | sed -e "s/\/fko_atlconf$//"`
gcc=`grep " GCC = " Make.inc | sed -e "s/   GCC = //"`
flags=`grep " GCCFLAGS = " Make.inc | sed -e "s/   GCCFLAGS = //"`
cd bin ; make xextract ; cd ..
ext=$blddir/bin/xextract
if [ ! -x $ext ]
then
   echo "UNABLE TO FIND/BUILD bin/xextract!!"
   exit 2
fi
arch=`grep " ARCHDEFS = " Make.inc | sed -e "s/   ARCHDEFS = //"`
echo "\n"
echo $path
echo $blddir
echo $gcc
echo $flags
echo $ext
echo $arch

mkdir fko
cd fko
$path/configure "$ext" "$gcc" "$flags" "$arch"
#cd bin
#make fko
#cd ../..
#echo "$blddir/fko/bin/fko | $gcc $flags -xassembler-with-cpp -" > FKO
