/* This file generated by /home/whaley/TEST/ATLAS3.9.21.3/obj64/..//tune/blas/gemm/txover.c
 */
#ifndef ATL_TXOVER_H
   #define ATL_TXOVER_H 1

   #define ATL_PDIM 3
static const int ATL_tmmNN_SQmnk_XO[3] = 
   {145,156,296};
static const int ATL_tmmNT_SQmnk_XO[3] = 
   {146,146,311};
static const int ATL_tmmTN_SQmnk_XO[3] = 
   {146,146,311};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
 ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[27] = 
   {0,0,0,0,0,0,2398,6085,0,1872,5319,0,1872,1949,0,332,510,3954,155,296,1165,155,294,908,0,72,5274};
static const int ATL_tmmNT_SmnLk_XO[27] = 
   {0,0,0,6571,0,0,2284,6123,0,2284,2284,0,535,1380,0,0,535,2604,153,291,964,153,289,892,0,72,5274};
static const int ATL_tmmTN_SmnLk_XO[27] = 
   {0,0,0,0,0,0,0,7989,0,0,7989,0,1128,1555,9394,316,526,3692,154,290,1498,154,293,904,0,72,5268};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
 ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[27] = 
   {6178,8818,0,3699,6892,0,2635,5051,0,2635,2854,7630,522,952,4076,0,522,2693,156,289,771,156,296,759,0,72,429};
static const int ATL_tmmNT_SmkLn_XO[27] = 
   {8270,0,0,6310,9253,0,3179,7121,0,3179,3179,0,511,1228,5106,0,511,2692,155,289,942,155,295,914,0,72,362};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
 ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[27] = 
   {0,0,0,0,0,0,0,0,0,0,6493,0,0,1689,0,309,509,2616,155,289,942,155,295,914,0,72,304};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[27] = 
   {0,0,0,8621,9898,0,6756,0,0,3513,4180,0,1133,1133,6517,310,511,2769,155,289,942,155,295,914,0,72,304};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
 ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[27] = 
   {296,574,1009,296,649,2420,273,491,2017,273,553,1827,164,504,1485,164,318,906,154,176,336,154,154,824,72,151,326};
static const int ATL_tmmNT_SmLnk_XO[27] = 
   {290,515,1092,290,509,1515,290,414,1360,290,372,1283,279,502,934,147,182,900,147,170,889,147,147,314,72,154,337};
static const int ATL_tmmTN_SmLnk_XO[27] = 
   {293,511,1117,293,554,2610,293,404,2075,293,457,1022,183,241,983,150,185,903,150,172,332,150,162,314,72,147,314};
static const int ATL_tmmTT_SmLnk_XO[27] = 
   {0,326,946,326,512,1521,326,417,1057,326,508,1350,166,345,918,155,189,896,155,166,896,155,167,291,72,151,326};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
 ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[27] = 
   {346,741,1582,346,762,1559,346,538,1497,179,504,1329,169,350,932,157,311,900,147,166,774,147,158,303,72,158,303};
static const int ATL_tmmNT_SnLmk_XO[27] = 
   {404,775,1846,404,770,1824,404,509,1546,271,513,1145,247,498,1360,150,185,903,150,161,892,150,150,638,72,158,303};
static const int ATL_tmmTN_SnLmk_XO[27] = 
   {431,770,2171,431,574,2157,411,523,1567,270,512,1346,161,386,1244,147,182,900,147,166,786,147,158,303,72,153,291};
static const int ATL_tmmTT_SnLmk_XO[27] = 
   {563,743,2346,563,572,2350,439,509,2337,285,510,1580,169,479,1367,159,346,900,147,158,889,147,158,303,72,158,303};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
 ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[27] = 
   {0,0,676,0,0,676,0,438,827,206,281,691,206,206,647,144,180,543,144,167,521,144,155,453,72,153,291};
static const int ATL_tmmNT_SkLmn_XO[27] = 
   {0,542,552,0,542,616,0,421,829,308,319,681,144,206,647,144,180,532,144,155,521,144,155,453,72,153,291};
static const int ATL_tmmTN_SkLmn_XO[27] = 
   {0,0,682,0,0,682,0,432,834,0,288,756,202,232,656,155,179,553,155,169,393,155,167,453,72,153,291};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
 ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
