/* This file generated by /home/whaley/TEST/ATLAS3.9.21.3/obj64/..//tune/blas/gemm/txover.c
 */
#ifndef ATL_TXOVER_H
   #define ATL_TXOVER_H 1

   #define ATL_PDIM 3
static const int ATL_tmmNN_SQmnk_XO[3] = 
   {112,121,247};
static const int ATL_tmmNT_SQmnk_XO[3] = 
   {115,130,240};
static const int ATL_tmmTN_SQmnk_XO[3] = 
   {113,113,240};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
 ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[27] = 
   {0,0,0,5159,0,0,2136,3693,0,2136,4584,0,463,2534,0,397,1540,5554,175,350,5269,56,61,1359,0,56,164};
static const int ATL_tmmNT_SmnLk_XO[27] = 
   {6035,0,0,4856,7824,0,2399,3658,0,1538,2916,0,434,1785,0,241,709,4453,175,439,4524,56,131,1142,0,56,133};
static const int ATL_tmmTN_SmnLk_XO[27] = 
   {0,0,0,6276,0,0,0,5504,0,0,5504,0,867,1486,0,248,794,0,171,262,6271,56,104,1084,0,56,162};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
 ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[27] = 
   {5362,7890,0,4374,4656,0,1661,3810,0,1661,2781,7673,393,1053,4070,393,426,2159,162,246,1686,56,65,366,0,56,181};
static const int ATL_tmmNT_SmkLn_XO[27] = 
   {0,0,0,0,0,0,2722,3615,0,1829,3214,9400,403,1336,4526,403,430,2149,149,430,1511,56,61,705,0,56,181};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
 ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[27] = 
   {0,0,0,0,0,0,0,0,0,0,6806,0,0,1484,0,0,419,3785,180,305,1939,56,61,763,0,56,220};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[27] = 
   {0,0,0,3769,9330,0,2860,0,0,2860,3205,0,445,948,0,445,455,3464,159,470,1666,56,60,686,0,56,220};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
 ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[27] = 
   {286,600,1780,286,473,1557,286,465,1334,286,377,1283,169,250,1033,169,203,688,114,213,278,70,115,438,56,60,205};
static const int ATL_tmmNT_SmLnk_XO[27] = 
   {286,749,1736,286,578,1423,286,534,1222,286,448,1165,190,271,917,179,242,691,117,154,252,56,115,438,56,60,205};
static const int ATL_tmmTN_SmLnk_XO[27] = 
   {282,485,1733,282,588,1174,282,463,1174,282,442,1130,175,220,798,161,207,770,116,206,271,63,117,450,56,63,171};
static const int ATL_tmmTT_SmLnk_XO[27] = 
   {221,389,1304,221,589,1168,221,471,1168,221,453,1100,221,251,1014,173,233,710,113,218,309,67,118,372,60,64,194};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
 ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[27] = 
   {287,581,1335,287,583,1513,287,523,1179,287,442,1147,168,345,1091,157,157,687,113,168,715,80,121,264,56,63,171};
static const int ATL_tmmNT_SnLmk_XO[27] = 
   {291,451,1316,291,589,1383,291,471,1182,291,438,1156,179,271,917,179,243,701,116,137,706,56,125,334,56,63,171};
static const int ATL_tmmTN_SnLmk_XO[27] = 
   {287,608,1536,287,593,1513,287,504,1156,287,312,1138,212,270,916,178,178,670,119,203,613,56,129,252,56,62,159};
static const int ATL_tmmTT_SnLmk_XO[27] = 
   {285,629,1623,285,591,1511,285,519,1489,285,449,1153,175,356,1149,115,214,907,115,135,694,56,134,264,56,77,171};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
 ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[27] = 
   {285,329,0,285,336,842,285,293,831,285,285,759,218,218,619,177,198,494,116,137,380,56,113,287,56,71,136};
static const int ATL_tmmNT_SkLmn_XO[27] = 
   {281,347,0,281,307,849,281,289,827,281,281,809,172,172,701,128,128,484,117,126,380,56,137,275,56,61,136};
static const int ATL_tmmTN_SkLmn_XO[27] = 
   {280,324,0,280,342,849,280,288,827,280,280,755,213,213,605,173,192,391,116,116,380,56,123,275,56,61,136};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
 ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
