/* This file generated by /home/whaley/TEST/ATLAS3.9.21.3/obj64/..//tune/blas/gemm/txover.c
 */
#ifndef ATL_TXOVER_H
   #define ATL_TXOVER_H 1

   #define ATL_PDIM 3
static const int ATL_tmmNN_SQmnk_XO[3] = 
   {172,172,341};
static const int ATL_tmmNT_SQmnk_XO[3] = 
   {172,172,341};
static const int ATL_tmmTN_SQmnk_XO[3] = 
   {172,172,341};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
 ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[27] = 
   {5198,0,0,4264,4990,0,1123,2304,0,1123,2104,6925,361,570,3233,178,343,1062,178,2225,4699,178,336,685,0,84,6144};
static const int ATL_tmmNT_SmnLk_XO[27] = 
   {0,4846,0,0,3613,0,1316,1621,0,645,1894,5247,343,618,3600,178,345,849,178,2225,4699,178,336,685,0,84,6144};
static const int ATL_tmmTN_SmnLk_XO[27] = 
   {0,0,0,5374,7432,0,1945,2403,0,1488,1603,0,385,399,3966,178,343,1062,178,2239,4577,178,336,685,0,84,6144};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
 ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[27] = 
   {4251,4797,0,0,2306,0,0,2306,0,857,1048,4305,373,386,2499,178,345,849,178,350,681,178,336,685,0,84,346};
static const int ATL_tmmNT_SmkLn_XO[27] = 
   {0,5862,0,0,3115,0,0,1988,0,1130,1278,5484,334,386,2499,178,337,1032,178,350,681,178,336,685,0,84,346};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
 ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[27] = 
   {0,0,0,3709,4178,0,3709,4780,0,0,1354,0,338,376,2133,178,343,1062,178,350,681,178,336,685,0,84,346};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[27] = 
   {0,0,0,1847,4154,0,1847,3326,0,1046,1324,5724,336,359,2499,178,337,1032,178,350,681,178,336,685,0,84,346};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
 ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[27] = 
   {168,200,512,168,377,407,168,199,676,168,289,362,168,204,362,168,179,347,0,168,347,168,180,343,84,180,343};
static const int ATL_tmmNT_SmLnk_XO[27] = 
   {369,490,661,168,477,961,168,453,676,168,286,931,168,180,362,0,168,347,0,168,347,168,180,343,84,180,343};
static const int ATL_tmmTN_SmLnk_XO[27] = 
   {168,198,497,168,207,482,168,199,676,168,289,362,168,268,347,168,179,347,0,168,347,168,180,343,84,180,343};
static const int ATL_tmmTT_SmLnk_XO[27] = 
   {168,197,407,168,522,856,168,183,676,168,289,362,168,204,362,0,168,347,0,168,347,168,180,343,84,180,343};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
 ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[27] = 
   {178,351,2208,178,510,2208,178,235,923,178,186,729,0,178,356,0,178,341,0,178,341,178,178,588,84,180,343};
static const int ATL_tmmNT_SnLmk_XO[27] = 
   {0,275,1715,0,205,1073,178,312,968,178,220,729,0,178,356,0,178,341,0,178,341,178,178,588,84,180,343};
static const int ATL_tmmTN_SnLmk_XO[27] = 
   {269,341,505,178,290,580,178,0,416,178,279,341,0,178,341,0,178,341,0,178,341,178,178,588,84,180,343};
static const int ATL_tmmTT_SnLmk_XO[27] = 
   {178,0,505,178,220,729,178,438,669,178,191,401,0,178,356,0,178,341,0,178,341,178,178,588,84,180,343};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
 ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[27] = 
   {0,168,362,0,168,347,0,168,407,0,168,407,168,181,377,0,168,362,0,168,347,168,180,343,84,180,343};
static const int ATL_tmmNT_SkLmn_XO[27] = 
   {180,190,343,0,180,343,0,180,572,0,168,407,0,168,377,0,168,347,0,168,347,168,180,343,84,180,343};
static const int ATL_tmmTN_SkLmn_XO[27] = 
   {0,179,372,0,179,342,0,179,542,0,168,407,168,181,377,0,168,347,0,168,347,168,180,343,84,180,343};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
 ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
