/* This file generated by /home/whaley/TEST/ATLAS3.9.22/obj64/..//tune/blas/gemm/txover.c
 */
#ifndef ATL_TXOVER_H
   #define ATL_TXOVER_H 1

   #define ATL_PDIM 2
static const int ATL_tmmNN_SQmnk_XO[2] = 
   {115,115};
static const int ATL_tmmNT_SQmnk_XO[2] = 
   {115,115};
static const int ATL_tmmTN_SQmnk_XO[2] = 
   {115,115};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
 ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[18] = 
   {6400,0,1600,0,1600,3600,1600,2405,216,1705,216,380,119,226,56,63,56,63};
static const int ATL_tmmNT_SmnLk_XO[18] = 
   {4177,4700,0,3507,1750,1750,729,2280,213,653,213,374,160,242,56,63,0,56};
static const int ATL_tmmTN_SmnLk_XO[18] = 
   {0,0,6716,10000,2219,2669,1770,2661,880,1082,224,383,153,230,56,79,0,56};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
 ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[18] = 
   {0,4784,2898,3026,984,1705,984,984,221,554,221,236,121,230,56,686,0,56};
static const int ATL_tmmNT_SmkLn_XO[18] = 
   {3607,5804,0,3607,1477,2075,1477,1517,241,897,241,271,117,225,70,375,0,56};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
 ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[18] = 
   {0,0,0,0,6486,0,2973,3073,1475,5183,214,429,131,297,56,60,0,56};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[18] = 
   {0,7590,0,6495,6495,9484,589,6102,589,842,222,469,153,230,56,79,0,56};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
 ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[18] = 
   {177,244,177,188,177,369,177,177,121,181,113,135,113,113,56,113,56,61};
static const int ATL_tmmNT_SmLnk_XO[18] = 
   {0,170,170,249,170,193,148,318,124,135,113,124,113,113,56,113,56,61};
static const int ATL_tmmTN_SmLnk_XO[18] = 
   {319,319,308,674,308,363,308,718,0,308,114,239,114,132,63,113,56,61};
static const int ATL_tmmTT_SmLnk_XO[18] = 
   {0,177,0,177,177,188,177,319,113,135,113,124,113,113,56,113,56,61};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
 ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[18] = 
   {0,247,214,324,178,404,178,542,167,443,159,170,0,159,0,159,0,159};
static const int ATL_tmmNT_SnLmk_XO[18] = 
   {0,271,0,215,215,790,215,248,215,406,0,215,215,252,56,113,56,61};
static const int ATL_tmmTN_SnLmk_XO[18] = 
   {0,330,0,330,0,330,229,510,120,165,120,176,120,120,63,113,56,182};
static const int ATL_tmmTT_SnLmk_XO[18] = 
   {908,965,875,1055,0,875,0,875,0,131,120,142,120,120,63,113,56,73};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
 ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[18] = 
   {0,312,257,323,257,345,245,925,188,368,0,129,118,118,84,118,0,84};
static const int ATL_tmmNT_SkLmn_XO[18] = 
   {0,1919,293,357,188,562,188,1016,175,309,115,137,115,115,58,127,58,61};
static const int ATL_tmmTN_SkLmn_XO[18] = 
   {263,1002,263,385,263,340,0,263,0,263,0,263,263,443,61,136,56,252};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
 ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
