/* This file generated by /home/whaley/TEST/ATLAS3.9.21.3/obj64/..//tune/blas/gemm/txover.c
 */
#ifndef ATL_TXOVER_H
   #define ATL_TXOVER_H 1

   #define ATL_PDIM 3
static const int ATL_tmmNN_SQmnk_XO[3] = 
   {113,113,225};
static const int ATL_tmmNT_SQmnk_XO[3] = 
   {113,113,225};
static const int ATL_tmmTN_SQmnk_XO[3] = 
   {113,113,225};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
 ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[27] = 
   {0,0,0,0,0,0,1439,1863,0,822,1425,0,339,621,0,122,386,1121,122,232,687,0,56,117,0,56,0};
static const int ATL_tmmNT_SmnLk_XO[27] = 
   {3221,3461,0,1542,2546,0,900,0,0,900,1557,0,322,620,0,121,233,2181,121,230,564,0,56,117,0,0,56};
static const int ATL_tmmTN_SmnLk_XO[27] = 
   {0,0,0,5867,0,0,1754,2589,0,1453,2824,0,355,623,4989,120,376,2049,120,228,706,56,63,113,0,0,56};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
 ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[27] = 
   {0,4208,0,0,2628,0,0,1410,0,537,892,5199,311,399,1681,120,224,728,120,228,670,0,56,136,0,0,56};
static const int ATL_tmmNT_SmkLn_XO[27] = 
   {0,4492,0,2289,2492,0,1683,2874,0,871,957,5293,350,404,2141,121,224,786,121,231,717,0,56,136,0,0,56};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
 ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[27] = 
   {0,0,0,4410,0,0,4410,4513,0,0,1244,0,0,417,2507,119,225,739,119,224,729,0,56,252,0,0,56};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[27] = 
   {0,0,0,2395,4647,0,2395,3361,0,553,1172,5381,347,451,2141,121,224,728,121,230,647,0,56,125,0,0,56};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
 ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[27] = 
   {119,348,891,119,372,891,119,360,891,119,146,709,119,144,255,0,119,224,119,119,224,56,117,117,0,56,117};
static const int ATL_tmmNT_SmLnk_XO[27] = 
   {0,247,1149,119,378,876,119,238,709,119,164,709,119,136,255,0,119,224,119,119,224,56,117,117,0,56,117};
static const int ATL_tmmTN_SmLnk_XO[27] = 
   {0,166,497,119,253,694,119,199,376,119,175,300,119,136,255,0,119,255,119,119,224,56,117,117,0,56,117};
static const int ATL_tmmTT_SmLnk_XO[27] = 
   {119,167,1149,119,361,982,119,361,861,119,307,694,119,135,649,119,149,240,119,119,224,56,117,117,0,56,117};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
 ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[27] = 
   {197,395,1176,197,448,1147,197,236,737,134,374,573,119,185,543,0,119,255,119,129,224,56,116,194,0,56,132};
static const int ATL_tmmNT_SnLmk_XO[27] = 
   {130,162,1157,130,386,1157,130,384,1036,130,297,664,119,140,466,119,127,255,119,129,224,56,113,132,0,56,117};
static const int ATL_tmmTN_SnLmk_XO[27] = 
   {197,391,790,197,388,731,197,236,737,134,182,527,119,204,512,119,132,224,119,129,224,56,116,194,0,56,132};
static const int ATL_tmmTT_SnLmk_XO[27] = 
   {199,248,755,119,378,785,119,376,604,119,164,482,119,170,285,119,134,240,119,119,224,56,113,209,0,56,117};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
 ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[27] = 
   {0,151,647,0,151,316,0,151,376,119,135,376,0,119,270,0,119,270,119,119,224,56,119,224,56,61,224};
static const int ATL_tmmNT_SkLmn_XO[27] = 
   {0,186,379,0,186,438,0,186,415,0,145,370,0,113,279,0,113,249,113,113,240,56,119,224,0,56,224};
static const int ATL_tmmTN_SkLmn_XO[27] = 
   {0,150,411,124,132,411,124,140,381,124,130,300,0,119,255,0,119,224,119,119,224,56,119,224,0,56,224};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
 ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
