/* This file generated by /home/whaley/TEST/ATLAS3.9.22/obj64/..//tune/blas/gemm/txover.c
 */
#ifndef ATL_TXOVER_H
   #define ATL_TXOVER_H 1

   #define ATL_PDIM 2
static const int ATL_tmmNN_SQmnk_XO[2] = 
   {115,115};
static const int ATL_tmmNT_SQmnk_XO[2] = 
   {115,115};
static const int ATL_tmmTN_SQmnk_XO[2] = 
   {115,115};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
 ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[18] = 
   {2245,2986,1504,3000,800,930,380,3208,0,380,0,380,380,471,0,56,0,56};
static const int ATL_tmmNT_SmnLk_XO[18] = 
   {2348,2554,0,2348,0,2348,0,2348,0,2348,0,224,119,224,0,56,56,194};
static const int ATL_tmmTN_SmnLk_XO[18] = 
   {5878,0,2111,0,1023,1691,567,959,175,0,175,894,152,229,0,56,56,61};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
 ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[18] = 
   {0,3412,1643,0,1643,3172,163,0,163,834,163,1370,163,3120,56,159,0,56};
static const int ATL_tmmNT_SmkLn_XO[18] = 
   {0,2507,0,1530,0,1530,0,1331,227,0,0,227,159,241,0,56,0,56};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
 ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[18] = 
   {0,0,2181,0,2181,2854,703,780,241,314,120,234,120,229,0,56,56,171};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[18] = 
   {4739,4840,1638,2114,1638,4796,497,746,217,314,120,234,120,229,56,84,0,56};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
 ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[18] = 
   {147,147,117,1238,117,162,0,117,117,617,0,117,117,117,56,117,0,56};
static const int ATL_tmmNT_SmLnk_XO[18] = 
   {0,202,202,305,202,690,0,202,202,216,0,202,202,317,56,117,0,56};
static const int ATL_tmmTN_SmLnk_XO[18] = 
   {0,192,0,192,117,132,117,617,117,162,0,117,117,117,56,117,0,56};
static const int ATL_tmmTT_SmLnk_XO[18] = 
   {117,404,117,132,117,132,0,117,117,389,117,132,0,117,56,117,56,63};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
 ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[18] = 
   {0,154,124,139,124,214,0,124,124,132,0,117,117,117,56,117,0,56};
static const int ATL_tmmNT_SnLmk_XO[18] = 
   {0,162,0,162,0,162,0,162,0,117,0,117,0,117,0,117,0,56};
static const int ATL_tmmTN_SnLmk_XO[18] = 
   {132,147,0,132,0,132,0,117,117,2179,0,117,117,117,56,117,0,56};
static const int ATL_tmmTT_SnLmk_XO[18] = 
   {0,162,0,132,0,132,0,132,0,132,132,147,117,117,56,117,56,71};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
 ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[18] = 
   {117,147,0,117,0,117,0,117,117,374,0,117,117,117,56,117,56,71};
static const int ATL_tmmNT_SkLmn_XO[18] = 
   {139,154,0,139,139,154,0,139,0,124,0,124,124,124,63,124,0,63};
static const int ATL_tmmTN_SkLmn_XO[18] = 
   {117,147,0,117,0,117,0,117,0,117,117,132,117,117,56,224,0,56};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
 ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
