/* This file generated by /home/whaley/TEST/ATLAS3.9.22/obj64/..//tune/blas/gemm/txover.c
*/
#ifndef ATL_TXOVER_H
#define ATL_TXOVER_H 1

#define ATL_PDIM 2
static const int ATL_tmmNN_SQmnk_XO[2] =
{169,169};
static const int ATL_tmmNT_SQmnk_XO[2] =
{169,169};
static const int ATL_tmmTN_SQmnk_XO[2] =
{169,169};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[18] =
{3122,4301,2083,2642,857,4985,857,1262,266,340,173,4208,173,2251,173,346,0,84};
static const int ATL_tmmNT_SmnLk_XO[18] =
{0,2655,2655,0,0,723,723,2263,189,448,189,356,189,2251,173,346,0,84};
static const int ATL_tmmTN_SmnLk_XO[18] =
{5600,0,3047,4837,1020,1318,723,0,318,348,318,4519,318,2373,173,346,0,84};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[18] =
{0,2549,1023,2004,1023,2234,620,4228,214,0,214,1217,214,340,173,346,0,84};
static const int ATL_tmmNT_SmkLn_XO[18] =
{0,3405,1608,1705,0,933,0,662,173,1425,173,340,173,340,173,346,0,84};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[18] =
{0,0,1989,4242,0,1989,0,674,0,377,0,377,179,346,179,593,0,84};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[18] =
{0,7675,1078,3781,1078,4288,338,950,0,338,0,338,0,338,263,346,0,84};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[18] =
{0,191,0,191,0,191,0,191,0,191,0,191,177,191,177,177,117,175};
static const int ATL_tmmNT_SmLnk_XO[18] =
{0,190,190,428,0,190,0,190,0,190,0,190,0,190,0,190,0,190};
static const int ATL_tmmTN_SmLnk_XO[18] =
{0,175,175,189,0,175,175,189,0,175,0,175,0,175,175,175,84,175};
static const int ATL_tmmTT_SmLnk_XO[18] =
{0,175,175,369,0,175,175,309,0,175,0,175,0,175,175,175,84,175};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[18] =
{0,182,182,434,182,189,0,175,0,175,0,175,0,175,0,175,0,175};
static const int ATL_tmmNT_SnLmk_XO[18] =
{190,264,190,204,190,1160,0,175,0,175,0,175,175,309,175,175,84,175};
static const int ATL_tmmTN_SnLmk_XO[18] =
{0,253,253,267,253,428,0,175,0,175,0,175,0,175,175,175,84,175};
static const int ATL_tmmTT_SnLmk_XO[18] =
{175,189,175,219,0,175,0,175,0,175,0,175,175,189,175,175,84,175};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[18] =
{0,175,0,175,0,175,175,219,0,175,0,175,0,175,175,175,84,175};
static const int ATL_tmmNT_SkLmn_XO[18] =
{175,2206,0,175,0,175,0,175,0,175,0,175,0,175,175,175,84,175};
static const int ATL_tmmTN_SkLmn_XO[18] =
{0,175,0,175,0,175,0,175,0,175,0,175,0,175,175,175,84,175};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
