.. -*- rst -*-
.. vim: ft=rst

.. This rst format file contains commonly used link targets
   and name substitutions.

.. NOTE: reST targets are
   __not_case_sensitive__

.. math-atlas
.. _math-atlas: http://math-atlas.sourceforge.net
.. _`math-atlas github`: http://github.com/rcwhaley/math-atlas
.. _`math-atlas mailing list`: http://sourceforge.net/mailarchive/forum.php?forum_name=math-atlas-devel

.. git stuff
.. _git: http://git-scm.com/
.. _github: http://github.com
.. _github help: http://help.github.com
