/* generated by ATLAS/tune/sysinfo/cachesrch.c */
#ifndef ATLAS_CACHE_H
   #define ATLAS_CACHE_H 1

/* 
 * L1 is write-through.
 * Can fetch 1/2 lines of 64-bytes when bw limited to L2.
 */
#define L1C_SZ 32768
#define L1C_LS 128
#define L1C_NSET 32
#define L1C_NWAY 8
#define L1C_INCLUSIVE 1
#define L1C_NSHARE 1
#define L1C_SURE 1
#ifdef SREAL
   #define L1C_ELTS 8192
   #define L1C_LSELTS 32
#elif defined(DREAL) || defined(SCPLX)
   #define L1C_ELTS 4096
   #define L1C_LSELTS 16
#elif defined(DCPLX)
   #define L1C_ELTS 2048
   #define L1C_LSELTS 8
#endif

#define L2C_SZ 524288L
#define L2C_LS 128
#define L2C_NSET 512
#define L2C_NWAY 8
#define L2C_INCLUSIVE 1
#define L2C_NSHARE 2
#define L2C_SURE 1
#ifdef SREAL
   #define L2C_ELTS 131072L
   #define L2C_LSELTS 32
#elif defined(DREAL) || defined(SCPLX)
   #define L2C_ELTS 65536L
   #define L2C_LSELTS 16
#elif defined(DCPLX)
   #define L2C_ELTS 32768L
   #define L2C_LSELTS 8
#endif

#define L3C_SZ 10485760L
#define L3C_LS 128
#define L3C_NSET 4096
#define L3C_NWAY 20
#define L3C_INCLUSIVE 0
#define L3C_NSHARE 2
#define L3C_SURE 1
#ifdef SREAL
   #define L3C_ELTS 2621440
   #define L3C_LSELTS 32
#elif defined(DREAL) || defined(SCPLX)
   #define L3C_ELTS 1310720
   #define L3C_LSELTS 16
#elif defined(DCPLX)
   #define L3C_ELTS  655360
   #define L3C_LSELTS 8
#endif

#define LLPC_LVL 1
#define LLPC_SZ  L1C_SZ
#define LLPC_ELTS  L1C_ELTS
#define LLC_LVL 3
#define LLC_SZ  L3C_SZ
#define LLC_ELTS  L3C_ELTS

#endif /* end multiple inclusion guard */
