/* generated by ATLAS/tune/sysinfo/cachesrch.c */
#ifndef ATLAS_CACHE_H
   #define ATLAS_CACHE_H 1

#define L1C_SZ 32768
#ifdef SREAL
   #define L1C_ELTS 8192
#elif defined(DREAL) || defined(SCPLX)
   #define L1C_ELTS 4096
#elif defined(DCPLX)
   #define L1C_ELTS 2048
#endif

#define L2C_SZ 131072
#ifdef SREAL
   #define L2C_ELTS 32768
#elif defined(DREAL) || defined(SCPLX)
   #define L2C_ELTS 16384
#elif defined(DCPLX)
   #define L2C_ELTS 8192
#endif

#define L3C_SZ 1048576
#ifdef SREAL
   #define L3C_ELTS 262144
#elif defined(DREAL) || defined(SCPLX)
   #define L3C_ELTS 131072
#elif defined(DCPLX)
   #define L3C_ELTS 65536
#endif

#define LLPC_LVL 2
#define LLPC_SZ  L2C_SZ
#define LLPC_ELTS  L2C_ELTS
#define LLC_LVL 3
#define LLC_SZ  L3C_SZ
#define LLC_ELTS  L3C_ELTS

#endif /* end multiple inclusion guard */
