/* This file generated by /home/cborntra/REPOS/ATLAS/build/..//tune/blas/gemm/txover.c
 */
#ifndef ATL_TXOVER_H
   #define ATL_TXOVER_H 1

   #define ATL_PDIM 2
static const int ATL_tmmNN_SQmnk_XO[2] = 
   {156,156};
static const int ATL_tmmNT_SQmnk_XO[2] = 
   {156,156};
static const int ATL_tmmTN_SQmnk_XO[2] = 
   {156,156};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
 ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[18] = 
   {0,0,7526,0,4208,6806,0,2544,726,1422,170,337,170,322,170,325,0,78};
static const int ATL_tmmNT_SmnLk_XO[18] = 
   {5786,6408,0,5786,0,5786,1560,2189,849,2337,290,520,170,322,170,325,0,78};
static const int ATL_tmmTN_SmnLk_XO[18] = 
   {0,0,0,0,9660,0,2752,3111,815,1050,168,494,168,321,168,319,0,78};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
 ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[18] = 
   {4984,6653,3093,3956,3093,4729,1240,2409,748,820,168,321,168,321,168,319,78,164};
static const int ATL_tmmNT_SmkLn_XO[18] = 
   {4532,0,4532,0,4532,6336,1318,2584,509,4781,177,0,168,3393,168,319,78,164};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
 ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[18] = 
   {0,0,0,0,5029,8484,1575,2214,510,877,168,484,168,321,168,319,78,164};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[18] = 
   {7475,0,2977,6424,1829,3409,1303,1884,0,557,253,321,168,321,168,319,78,164};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
 ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[18] = 
   {323,368,279,485,250,1372,250,315,168,0,168,0,168,0,168,320,78,158};
static const int ATL_tmmNT_SmLnk_XO[18] = 
   {283,316,272,314,259,315,168,315,168,315,168,315,168,315,168,320,78,158};
static const int ATL_tmmTN_SmLnk_XO[18] = 
   {340,378,278,321,186,315,168,315,168,315,168,315,168,315,168,320,78,158};
static const int ATL_tmmTT_SmLnk_XO[18] = 
   {346,515,270,321,186,315,168,315,168,315,168,315,168,315,168,320,78,158};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
 ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[18] = 
   {327,372,283,316,250,315,168,315,168,327,168,327,168,327,168,320,78,158};
static const int ATL_tmmNT_SnLmk_XO[18] = 
   {338,514,258,350,204,315,168,315,168,315,168,315,168,315,168,320,78,158};
static const int ATL_tmmTN_SnLmk_XO[18] = 
   {0,513,314,363,286,314,259,315,168,315,168,315,168,315,168,320,78,158};
static const int ATL_tmmTT_SnLmk_XO[18] = 
   {440,472,307,472,307,316,250,315,168,315,168,315,168,315,168,320,78,158};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
 ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[18] = 
   {0,316,0,316,0,169,158,180,158,169,0,158,0,158,158,158,78,158};
static const int ATL_tmmNT_SkLmn_XO[18] = 
   {208,264,0,208,163,169,158,169,158,169,158,169,0,158,158,158,78,158};
static const int ATL_tmmTN_SkLmn_XO[18] = 
   {316,316,169,316,169,169,158,169,0,158,0,158,0,158,158,158,78,158};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
 ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
