/* This file generated by /home/cborntra/REPOS/ATLAS/build/..//tune/blas/gemm/txover.c
*/
#ifndef ATL_TXOVER_H
#define ATL_TXOVER_H 1

#define ATL_PDIM 2
static const int ATL_tmmNN_SQmnk_XO[2] =
{160,166};
static const int ATL_tmmNT_SQmnk_XO[2] =
{160,166};
static const int ATL_tmmTN_SQmnk_XO[2] =
{160,166};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[18] =
{0,0,0,0,0,0,0,3994,0,1073,324,324,172,324,172,327,0,80};
static const int ATL_tmmNT_SmnLk_XO[18] =
{0,6500,0,4572,2516,2516,1620,1620,0,677,286,538,172,324,172,327,0,80};
static const int ATL_tmmTN_SmnLk_XO[18] =
{0,0,0,0,0,0,0,4033,0,909,284,323,170,323,170,321,0,80};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[18] =
{0,5260,0,5260,0,4052,0,2233,0,880,303,323,170,323,170,321,80,166};
static const int ATL_tmmNT_SmkLn_XO[18] =
{0,0,0,9652,0,6294,0,2351,0,851,0,323,170,323,170,321,80,166};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[18] =
{0,0,0,0,8090,8344,0,2936,869,918,303,323,170,323,170,321,80,166};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[18] =
{0,0,0,7472,2648,3567,0,2648,865,946,303,323,170,323,170,321,80,166};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[18] =
{334,367,0,334,279,325,179,329,170,329,170,329,170,329,170,322,80,160};
static const int ATL_tmmNT_SmLnk_XO[18] =
{330,750,330,344,289,329,170,329,170,329,170,329,170,329,170,322,80,160};
static const int ATL_tmmTN_SmLnk_XO[18] =
{316,537,316,459,269,329,170,329,170,329,170,329,170,329,170,322,80,160};
static const int ATL_tmmTT_SmLnk_XO[18] =
{440,503,303,352,275,325,259,329,170,329,170,329,170,329,170,322,80,160};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[18] =
{0,568,314,331,265,340,170,329,170,329,170,329,170,340,170,322,80,160};
static const int ATL_tmmNT_SnLmk_XO[18] =
{323,743,0,323,279,329,170,329,170,329,170,329,170,329,170,322,80,160};
static const int ATL_tmmTN_SnLmk_XO[18] =
{378,454,378,432,288,325,179,329,170,329,170,329,170,329,170,322,80,160};
static const int ATL_tmmTT_SnLmk_XO[18] =
{371,670,303,348,259,329,170,329,170,329,170,329,170,329,170,322,80,160};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[18] =
{351,650,282,328,0,182,171,182,0,160,0,160,0,160,160,160,80,160};
static const int ATL_tmmNT_SkLmn_XO[18] =
{0,480,280,330,0,171,160,171,160,171,0,160,0,160,160,160,80,160};
static const int ATL_tmmTN_SkLmn_XO[18] =
{0,340,0,205,160,171,160,171,0,160,0,160,0,160,160,160,80,160};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
