/* This file generated by /home/whaley/TEST/ATLAS3.9.23.0/obj64/..//tune/blas/gemm/txover.c
*/
#ifndef ATL_TXOVER_H
#define ATL_TXOVER_H 1

#define ATL_PDIM 2
static const int ATL_tmmNN_SQmnk_XO[2] =
{144,144};
static const int ATL_tmmNT_SQmnk_XO[2] =
{144,144};
static const int ATL_tmmTN_SQmnk_XO[2] =
{144,144};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[18] =
{0,6678,0,4981,0,1962,710,798,238,290,153,290,153,290,153,288,0,72};
static const int ATL_tmmNT_SmnLk_XO[18] =
{0,4252,0,3717,0,1910,612,643,153,290,153,290,153,290,153,288,0,72};
static const int ATL_tmmTN_SmnLk_XO[18] =
{0,0,0,6209,0,2546,728,798,238,290,153,290,153,290,153,288,0,72};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[18] =
{0,3611,0,2599,1087,1087,0,565,153,290,153,290,153,290,153,288,0,72};
static const int ATL_tmmNT_SmkLn_XO[18] =
{0,4433,0,2692,1069,1088,503,768,238,290,153,290,153,290,153,288,0,72};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[18] =
{0,0,2689,0,919,2055,541,844,238,290,153,290,153,290,153,288,0,72};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[18] =
{0,0,3080,5119,911,2048,533,828,238,290,153,290,153,290,153,288,0,72};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[18] =
{148,178,148,163,148,163,148,163,0,148,0,148,0,148,148,148,72,148};
static const int ATL_tmmNT_SmLnk_XO[18] =
{148,163,148,163,148,163,0,148,0,148,0,148,0,148,148,148,72,148};
static const int ATL_tmmTN_SmLnk_XO[18] =
{148,178,148,163,148,163,0,148,0,148,0,148,0,148,148,148,72,148};
static const int ATL_tmmTT_SmLnk_XO[18] =
{148,178,148,163,148,163,0,148,0,148,0,148,0,148,148,148,72,148};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[18] =
{148,178,148,283,0,148,0,148,0,148,0,148,0,148,148,148,72,148};
static const int ATL_tmmNT_SnLmk_XO[18] =
{148,178,148,163,0,148,0,148,0,148,0,148,0,148,148,148,72,148};
static const int ATL_tmmTN_SnLmk_XO[18] =
{148,178,148,163,0,148,0,148,0,148,0,148,0,148,148,148,72,148};
static const int ATL_tmmTT_SnLmk_XO[18] =
{148,178,148,163,148,163,0,148,0,148,0,148,0,148,148,148,72,148};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[18] =
{0,148,0,148,0,148,0,148,0,148,0,148,0,148,148,148,72,148};
static const int ATL_tmmNT_SkLmn_XO[18] =
{0,148,0,148,0,148,0,148,0,148,0,148,0,148,148,148,72,148};
static const int ATL_tmmTN_SkLmn_XO[18] =
{148,163,0,148,0,148,0,148,0,148,0,148,0,148,148,148,72,148};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
