/* This file generated by /home/whaley/TEST/ATLAS3.9.23.0/obj64/..//tune/blas/gemm/txover.c
 */
#ifndef ATL_TXOVER_H
   #define ATL_TXOVER_H 1

   #define ATL_PDIM 3
static const int ATL_tmmNN_SQmnk_XO[3] = 
   {100,100,188};
static const int ATL_tmmNT_SQmnk_XO[3] = 
   {96,103,174};
static const int ATL_tmmTN_SQmnk_XO[3] = 
   {100,100,188};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
 ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[27] = 
   {0,3445,0,0,1783,0,1373,1373,0,535,633,2093,187,217,1257,100,198,297,100,202,295,0,48,101,0,0,48};
static const int ATL_tmmNT_SmnLk_XO[27] = 
   {2837,2914,0,0,1685,0,0,1008,3893,0,596,1874,0,222,1461,0,222,297,100,202,295,0,48,101,0,0,48};
static const int ATL_tmmTN_SmnLk_XO[27] = 
   {0,0,0,0,3230,0,1973,1973,5661,587,739,3010,202,237,1366,99,194,536,99,199,291,0,48,105,0,0,48};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
 ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[27] = 
   {0,2203,5643,0,2203,3152,0,0,2203,2203,4371,0,517,1097,1682,122,301,534,97,194,408,0,48,105,0,0,48};
static const int ATL_tmmNT_SmkLn_XO[27] = 
   {0,2805,0,0,2805,4340,0,0,2206,2206,4372,0,522,1101,1686,127,318,537,100,200,396,0,48,105,0,0,48};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
 ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[27] = 
   {0,0,0,0,5179,0,0,2249,5296,2249,4338,0,406,1043,1678,117,237,502,100,200,396,0,48,105,0,0,48};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[27] = 
   {4081,4208,0,2179,2179,0,1010,1010,3752,0,674,1498,180,192,468,100,200,422,100,200,396,0,48,105,0,0,48};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
 ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[27] = 
   {0,127,246,0,110,413,0,110,420,0,101,420,101,120,405,0,101,389,101,101,171,48,101,101,0,48,101};
static const int ATL_tmmNT_SmLnk_XO[27] = 
   {0,133,426,0,124,411,0,124,396,124,148,405,101,119,389,0,101,389,101,101,171,48,101,101,0,48,101};
static const int ATL_tmmTN_SmLnk_XO[27] = 
   {101,111,435,0,101,420,101,110,420,0,101,405,0,101,405,0,101,389,101,101,171,48,101,101,0,48,101};
static const int ATL_tmmTT_SmLnk_XO[27] = 
   {0,122,424,0,122,394,0,122,409,122,145,388,100,119,404,0,100,404,100,100,387,48,101,101,0,48,101};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
 ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[27] = 
   {0,128,421,0,119,406,0,119,404,0,100,404,100,118,388,0,100,388,100,100,202,48,100,202,0,48,101};
static const int ATL_tmmNT_SnLmk_XO[27] = 
   {0,123,215,0,110,413,0,110,405,0,101,405,101,119,389,0,101,389,101,101,171,48,100,202,0,48,101};
static const int ATL_tmmTN_SnLmk_XO[27] = 
   {100,109,419,0,100,419,100,109,419,0,100,404,100,109,388,0,100,404,100,100,202,48,100,202,0,48,101};
static const int ATL_tmmTT_SnLmk_XO[27] = 
   {0,128,436,0,119,421,0,119,404,0,100,404,100,118,388,0,100,388,100,100,202,48,100,202,0,48,101};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
 ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[27] = 
   {109,131,199,109,118,184,109,262,397,109,109,388,100,127,388,0,100,388,100,100,202,48,100,202,0,48,101};
static const int ATL_tmmNT_SkLmn_XO[27] = 
   {0,122,197,0,122,182,122,232,394,122,190,388,100,136,388,0,100,388,100,100,202,48,100,202,0,48,202};
static const int ATL_tmmTN_SkLmn_XO[27] = 
   {100,109,388,0,100,388,100,109,388,0,100,388,0,100,388,0,100,388,100,100,202,48,101,101,0,48,101};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
 ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
