/* This file generated by /home/whaley/TEST/ATLAS3.9.23.0/obj64/..//tune/blas/gemm/txover.c
*/
#ifndef ATL_TXOVER_H
#define ATL_TXOVER_H 1

#define ATL_PDIM 3
static const int ATL_tmmNN_SQmnk_XO[3] =
{136,136,191};
static const int ATL_tmmNT_SQmnk_XO[3] =
{136,141,541};
static const int ATL_tmmTN_SQmnk_XO[3] =
{140,140,140};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[27] =
{0,4037,0,0,2487,7090,0,2181,5949,708,756,2676,257,283,1741,147,284,590,147,275,422,147,280,408,0,68,1183};
static const int ATL_tmmNT_SmnLk_XO[27] =
{0,2833,0,2095,2373,6736,0,1262,5252,673,673,4377,273,483,1311,147,275,422,147,275,559,147,280,408,0,68,640};
static const int ATL_tmmTN_SmnLk_XO[27] =
{0,0,0,0,3969,0,2737,2804,7885,660,791,3025,237,280,1373,147,284,590,147,275,422,147,280,408,0,68,98};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[27] =
{0,2635,6070,0,2635,4465,0,1537,2018,1164,2399,3664,293,699,1219,147,280,575,147,275,559,147,280,408,0,68,206};
static const int ATL_tmmNT_SmkLn_XO[27] =
{0,4314,0,0,4314,6573,0,1912,3148,1912,3988,6112,448,990,1588,147,280,575,147,275,559,147,280,408,0,68,206};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[27] =
{0,0,0,4947,4947,0,1698,1797,7146,1168,2403,3667,298,632,1219,147,284,590,147,275,559,147,280,408,0,68,144};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[27] =
{0,4079,0,2662,2662,0,0,1169,4797,1169,2404,3667,299,635,1189,147,284,590,147,275,559,147,280,408,0,68,144};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[27] =
{0,182,584,182,0,211,0,136,301,136,146,301,0,136,286,0,136,286,0,136,286,136,136,251,68,136,205};
static const int ATL_tmmNT_SmLnk_XO[27] =
{0,211,579,211,0,211,0,136,301,136,163,286,0,136,286,0,136,286,0,136,286,136,136,251,68,136,205};
static const int ATL_tmmTN_SmLnk_XO[27] =
{0,160,318,0,138,288,0,138,303,0,138,288,0,138,288,0,138,288,0,138,288,138,148,282,68,136,205};
static const int ATL_tmmTT_SmLnk_XO[27] =
{0,160,318,0,138,288,0,138,303,138,156,288,0,138,288,0,138,288,0,138,288,138,148,282,68,136,205};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[27] =
{0,158,303,0,138,288,0,138,303,138,147,288,0,138,288,0,138,258,0,138,258,138,148,282,68,144,144};
static const int ATL_tmmNT_SnLmk_XO[27] =
{0,148,388,0,148,343,0,148,303,138,156,288,0,138,288,0,138,288,0,138,288,138,148,282,68,136,159};
static const int ATL_tmmTN_SnLmk_XO[27] =
{0,160,318,0,138,288,0,138,303,0,138,303,0,138,288,0,138,288,0,138,258,138,148,282,68,144,144};
static const int ATL_tmmTT_SnLmk_XO[27] =
{0,194,579,194,0,228,0,138,303,138,156,288,0,138,288,0,138,288,0,138,288,138,148,282,68,144,144};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[27] =
{0,147,282,0,147,267,147,175,288,138,147,288,0,138,288,0,138,288,0,138,273,138,148,282,68,144,144};
static const int ATL_tmmNT_SkLmn_XO[27] =
{0,168,287,0,168,257,168,252,305,140,177,290,0,140,290,0,140,275,0,140,275,140,140,235,68,144,144};
static const int ATL_tmmTN_SkLmn_XO[27] =
{0,140,305,0,140,305,0,140,290,0,140,290,0,140,290,0,140,275,0,140,275,140,140,235,68,144,144};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
