@lan F
@inc purp
*  Purpose
*  =======
@inc arg
*  Arguments
*  =========
@inc note
*  Notes
*  =====
@inc detail
*  Further Details
*  ===============
@inc in_param
*  Internal Parameters
*  ===================
@inc dotdot
*     ..
@inc sarg
*     .. Scalar Arguments ..
@inc aarg
*     .. Array Arguments ..
@inc subarg
*     .. Subroutine Arguments ..
@inc farg
*     .. Function Arguments ..
@inc comline
*  =====================================================================
@inc param
*     .. Parameters ..
@inc sloc
*     .. Local Scalars ..
@inc aloc
*     .. Local Arrays ..
@inc vloc
*     .. Local Variables ..
@inc exsub
*     .. External Subroutines ..
@inc exfunc
*     .. External Functions ..
@inc infunc
*     .. Intrinsic Functions ..
@inc statfunc
*     .. Statement Functions ..
@inc common
*     .. Common Blocks ..
@inc data
*     .. Data Statements ..
@inc save
*     .. Save Statements ..
@inc equiv
*     .. Equivalence Statements ..
@inc exstat
*     .. Executable Statements ..
*
@inc tstin
*
*     Test the input parameters
*
@inc quick
*
*     Quick return if possible
*
@inc start
*
*     Start the operations
*
@inc gettype
*
*     Get type structure
*
@inc endofrout
*
      RETURN
*
*     End of @(rname)
*
      END
@inc !
@lan C
@inc purp
 * Purpose
 * =======
@inc arg
 * Arguments
 * =========
@inc note
 * Notes
 * =====
@inc detail
 * Further Details
 * ===============
@inc in_param
 * Internal Parameters
 * ===================
@inc dotdot
 * ..
@inc sarg
/*
 * .. Scalar Arguments ..
 */
@inc aarg
/*
 * .. Array Arguments ..
 */
@inc farg subarg
/*
 * .. Function Arguments ..
 */
@inc comline
 * ---------------------------------------------------------------------
@inc param
/*
 * .. Parameters ..
 */
@inc sloc
/*
 * .. Local Scalars ..
 */
@inc aloc
/*
 * .. Local Arrays ..
 */
@inc vloc
/*
 * .. Local Variables ..
 */
@inc exsub
/* ..
 * .. External Subroutines ..
 */
@inc exfunc exsub
/* ..
 * .. External Functions ..
 */
@inc exstat
/* ..
 * .. Executable Statements ..
 *
 */
@inc incf
/*
 * Include files
 */
@inc tstin
/*
 * Test the input parameters
 */
@inc quick
/*
 * Quick return if possible
 */
@inc start
/*
 * Start the operations
 */
@inc gettype
/*
 * Get type structure
 */
@inc endofrout
/*
 * End of @(rname)
 */
}
@inc !
@lan F C
