/* This file generated by /home/whaley/TEST/ATLAS3.9.23.1/obj64/..//tune/blas/gemm/txover.c
 */
#ifndef ATL_TXOVER_H
   #define ATL_TXOVER_H 1

   #define ATL_PDIM 2
static const int ATL_tmmNN_SQmnk_XO[2] = 
   {99,99};
static const int ATL_tmmNT_SQmnk_XO[2] = 
   {99,99};
static const int ATL_tmmTN_SQmnk_XO[2] = 
   {99,107};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
 ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[18] = 
   {0,0,5025,0,0,3468,1556,1903,425,529,115,223,100,203,0,48,0,48};
static const int ATL_tmmNT_SmnLk_XO[18] = 
   {5862,0,3977,7591,0,2773,1690,1889,479,539,157,192,100,203,0,48,0,48};
static const int ATL_tmmTN_SmnLk_XO[18] = 
   {0,0,0,0,6819,7505,2019,2122,489,535,171,207,111,193,0,48,0,48};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
 ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[18] = 
   {5589,7704,5102,7455,2599,3169,1345,1654,420,1406,157,193,97,193,0,48,0,48};
static const int ATL_tmmNT_SmkLn_XO[18] = 
   {0,0,7813,8462,0,3850,1351,1873,481,725,169,193,97,193,0,48,0,48};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
 ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[18] = 
   {0,0,0,0,5098,5098,1745,2199,492,744,169,193,97,193,0,48,0,48};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[18] = 
   {9927,0,5359,6192,2385,3853,0,1719,494,734,169,193,97,193,0,48,0,48};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
 ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[18] = 
   {181,293,181,327,181,221,0,142,120,120,97,120,97,105,48,105,48,53};
static const int ATL_tmmNT_SmLnk_XO[18] = 
   {146,214,0,146,146,225,146,211,0,108,97,120,97,105,48,105,48,53};
static const int ATL_tmmTN_SmLnk_XO[18] = 
   {188,448,188,323,188,218,139,182,114,131,97,108,97,105,48,105,48,53};
static const int ATL_tmmTT_SmLnk_XO[18] = 
   {162,321,162,332,162,286,162,188,120,120,97,120,97,105,48,105,48,53};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
 ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[18] = 
   {162,332,162,321,162,298,162,188,120,120,97,108,97,105,48,105,48,53};
static const int ATL_tmmNT_SnLmk_XO[18] = 
   {159,329,159,329,159,306,159,211,0,108,97,120,97,105,48,105,48,53};
static const int ATL_tmmTN_SnLmk_XO[18] = 
   {142,450,142,175,142,221,0,142,120,120,97,108,97,105,48,105,48,53};
static const int ATL_tmmTT_SnLmk_XO[18] = 
   {177,323,177,323,177,312,177,177,0,121,98,109,98,129,48,105,48,53};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
 ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[18] = 
   {244,288,244,468,244,324,165,211,0,120,97,108,97,105,48,105,48,53};
static const int ATL_tmmNT_SkLmn_XO[18] = 
   {246,268,246,257,246,329,183,222,0,120,97,108,97,105,48,105,48,53};
static const int ATL_tmmTN_SkLmn_XO[18] = 
   {246,290,246,257,246,329,183,222,0,120,97,108,97,105,48,105,48,65};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
 ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
