/* This file generated by /home/whaley/TEST/ATLAS3.9.23.0/obj64/..//tune/blas/gemm/txover.c
*/
#ifndef ATL_TXOVER_H
#define ATL_TXOVER_H 1

#define ATL_PDIM 2
static const int ATL_tmmNN_SQmnk_XO[2] =
{146,151};
static const int ATL_tmmNT_SQmnk_XO[2] =
{144,144};
static const int ATL_tmmTN_SQmnk_XO[2] =
{144,144};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[18] =
{0,0,0,0,4107,5758,1169,1673,433,581,153,290,153,290,153,288,0,72};
static const int ATL_tmmNT_SmnLk_XO[18] =
{0,0,0,0,3301,5211,1138,1657,552,565,153,290,153,290,153,288,0,72};
static const int ATL_tmmTN_SmnLk_XO[18] =
{0,0,0,0,4023,6131,1313,2155,617,683,155,288,155,288,155,294,0,72};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[18] =
{0,0,6690,0,2941,4007,1383,1663,472,2692,155,288,155,288,155,294,0,72};
static const int ATL_tmmNT_SmkLn_XO[18] =
{0,0,8322,8606,2571,5144,1714,1944,476,798,155,288,155,288,155,294,0,72};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[18] =
{0,0,0,0,6346,7349,1519,2020,630,789,155,288,155,288,155,294,0,72};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[18] =
{0,0,7470,9533,4034,5029,0,1845,491,827,155,288,155,288,155,294,0,72};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[18] =
{198,321,198,231,0,198,176,185,152,174,152,163,0,152,152,152,72,152};
static const int ATL_tmmNT_SmLnk_XO[18] =
{197,320,0,197,0,197,152,174,152,163,152,163,0,152,152,152,72,152};
static const int ATL_tmmTN_SmLnk_XO[18] =
{218,319,218,240,218,230,0,185,152,254,152,163,0,152,152,152,72,152};
static const int ATL_tmmTT_SmLnk_XO[18] =
{197,320,197,242,0,197,152,174,152,163,152,163,0,152,152,152,72,152};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[18] =
{174,321,174,219,174,230,174,174,152,174,152,163,0,152,152,164,72,152};
static const int ATL_tmmNT_SnLmk_XO[18] =
{174,321,174,196,174,242,174,174,152,163,152,163,0,152,152,152,72,152};
static const int ATL_tmmTN_SnLmk_XO[18] =
{216,317,216,227,216,242,0,174,152,163,152,163,0,152,152,152,72,152};
static const int ATL_tmmTT_SnLmk_XO[18] =
{243,320,0,243,243,299,152,185,152,163,152,163,0,152,152,152,72,164};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[18] =
{218,229,0,218,218,320,185,197,152,185,152,163,0,152,152,152,72,152};
static const int ATL_tmmNT_SkLmn_XO[18] =
{0,223,0,223,223,253,174,174,152,163,152,163,0,152,152,152,72,152};
static const int ATL_tmmTN_SkLmn_XO[18] =
{224,235,0,224,224,263,185,185,152,163,152,163,0,152,152,152,72,152};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
