/* This file generated by /home/whaley/TEST/ATLAS3.9.21.8/obj64/..//tune/blas/gemm/txover.c
 */
#ifndef ATL_TXOVER_H
   #define ATL_TXOVER_H 1

   #define ATL_PDIM 3
static const int ATL_tmmNN_SQmnk_XO[3] = 
   {163,163,324};
static const int ATL_tmmNT_SQmnk_XO[3] = 
   {163,163,324};
static const int ATL_tmmTN_SQmnk_XO[3] = 
   {163,163,324};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
 ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[27] = 
   {0,0,0,0,0,0,6261,6461,0,0,2208,0,0,587,2983,170,327,704,170,332,643,170,320,651,0,80,5896};
static const int ATL_tmmNT_SmnLk_XO[27] = 
   {0,0,0,0,0,0,4618,4909,0,1819,2200,8000,576,576,2983,170,327,674,170,332,643,170,320,651,0,80,5896};
static const int ATL_tmmTN_SmnLk_XO[27] = 
   {0,0,0,0,0,0,0,6946,0,0,1879,0,395,621,2861,170,321,1055,170,332,643,170,320,651,0,80,5896};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
 ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[27] = 
   {0,0,0,6067,0,0,3421,0,0,675,2277,0,675,839,2138,184,642,1086,170,332,643,170,320,651,0,80,172};
static const int ATL_tmmNT_SmkLn_XO[27] = 
   {6527,7079,0,0,6527,0,3513,3596,0,955,1296,0,0,571,5307,170,329,1025,170,332,643,170,320,651,0,80,172};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
 ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[27] = 
   {0,0,0,0,0,0,6534,6534,0,1302,2562,0,596,805,5185,170,327,842,170,332,643,170,320,651,0,80,172};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[27] = 
   {6663,0,0,0,5148,0,3321,3321,0,1195,1336,7881,436,541,2493,170,329,1025,170,332,643,170,320,651,0,80,172};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
 ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[27] = 
   {298,298,1116,0,272,1641,181,502,1164,0,181,538,181,258,454,171,186,424,0,171,320,171,171,325,80,171,171};
static const int ATL_tmmNT_SmLnk_XO[27] = 
   {0,270,2948,0,260,0,171,196,3401,171,472,2204,171,186,424,171,191,335,0,171,320,171,171,325,80,171,171};
static const int ATL_tmmTN_SmLnk_XO[27] = 
   {299,299,697,0,243,1034,0,243,957,183,372,933,171,187,439,0,171,335,0,171,320,171,171,325,80,171,171};
static const int ATL_tmmTT_SmLnk_XO[27] = 
   {0,282,2366,0,266,0,177,183,3401,171,481,2324,171,186,424,171,222,335,0,171,335,171,171,325,80,171,171};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
 ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[27] = 
   {0,272,0,0,199,3880,171,445,2025,0,171,948,0,171,350,171,193,350,0,171,320,171,171,325,80,171,171};
static const int ATL_tmmNT_SnLmk_XO[27] = 
   {288,288,0,200,200,0,171,181,2922,0,171,993,171,186,663,171,193,350,0,171,320,171,171,325,80,171,171};
static const int ATL_tmmTN_SnLmk_XO[27] = 
   {0,382,678,382,489,992,0,246,978,171,294,454,171,186,424,0,171,350,0,171,320,171,171,325,80,171,171};
static const int ATL_tmmTT_SnLmk_XO[27] = 
   {287,505,1101,0,215,1307,171,440,993,0,171,918,0,171,320,171,193,350,0,171,320,171,171,325,80,171,171};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
 ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[27] = 
   {258,519,593,258,485,549,258,0,454,0,171,529,0,171,335,171,181,335,0,171,320,171,171,325,80,171,171};
static const int ATL_tmmNT_SkLmn_XO[27] = 
   {254,516,590,254,352,517,254,320,469,0,171,529,0,171,335,171,180,320,0,171,320,171,171,325,80,171,171};
static const int ATL_tmmTN_SkLmn_XO[27] = 
   {182,0,449,182,0,405,182,357,469,171,312,454,171,293,350,0,171,335,0,171,320,171,171,325,80,171,171};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
 ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
