/* This file generated by /home/whaley/atlas3.9/TEST/ATLAS//tune/blas/gemm/txover.c
 */
#ifndef ATL_TXOVER_H
   #define ATL_TXOVER_H 1

   #define ATL_PDIM 1
static const int ATL_tmmNN_SQmnk_XO[1] = 
   {166};
static const int ATL_tmmNT_SQmnk_XO[1] = 
   {166};
static const int ATL_tmmTN_SQmnk_XO[1] = 
   {166};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
 ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[9] = 
   {4563,3418,2251,172,172,172,172,172,80};
static const int ATL_tmmNT_SmnLk_XO[9] = 
   {4065,2862,1150,172,172,172,172,172,80};
static const int ATL_tmmTN_SmnLk_XO[9] = 
   {5809,4311,4311,385,172,172,172,172,80};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
 ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[9] = 
   {0,0,0,0,187,187,187,187,80};
static const int ATL_tmmNT_SmkLn_XO[9] = 
   {1461,1436,790,294,172,172,172,172,80};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
 ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[9] = 
   {0,0,0,324,172,172,172,172,80};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[9] = 
   {7213,812,581,342,342,342,342,342,80};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
 ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[9] = 
   {663,663,663,663,663,171,171,171,80};
static const int ATL_tmmNT_SmLnk_XO[9] = 
   {185,185,185,185,185,171,171,171,80};
static const int ATL_tmmTN_SmLnk_XO[9] = 
   {340,340,340,340,340,340,340,340,80};
static const int ATL_tmmTT_SmLnk_XO[9] = 
   {215,215,215,215,215,171,171,171,80};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
 ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[9] = 
   {185,185,185,185,185,171,171,171,80};
static const int ATL_tmmNT_SnLmk_XO[9] = 
   {185,185,185,185,185,171,171,171,80};
static const int ATL_tmmTN_SnLmk_XO[9] = 
   {171,171,171,171,171,171,171,171,80};
static const int ATL_tmmTT_SnLmk_XO[9] = 
   {185,185,185,185,185,171,171,171,80};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
 ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[9] = 
   {171,171,171,171,171,171,171,171,80};
static const int ATL_tmmNT_SkLmn_XO[9] = 
   {185,185,185,185,185,171,171,171,80};
static const int ATL_tmmTN_SkLmn_XO[9] = 
   {171,171,171,171,171,171,171,171,80};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
 ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
