/* This file generated by /home/whaley/atlas3.9/TEST/ATLAS//tune/blas/gemm/txover.c
 */
#ifndef ATL_TXOVER_H
   #define ATL_TXOVER_H 1

   #define ATL_PDIM 1
static const int ATL_tmmNN_SQmnk_XO[1] = 
   {166};
static const int ATL_tmmNT_SQmnk_XO[1] = 
   {173};
static const int ATL_tmmTN_SQmnk_XO[1] = 
   {166};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
 ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[9] = 
   {0,0,6279,661,172,172,172,172,80};
static const int ATL_tmmNT_SmnLk_XO[9] = 
   {0,0,7142,163,163,163,163,163,87};
static const int ATL_tmmTN_SmnLk_XO[9] = 
   {0,0,5800,1469,444,176,176,176,80};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
 ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[9] = 
   {0,5239,5239,328,175,166,166,166,80};
static const int ATL_tmmNT_SmkLn_XO[9] = 
   {0,0,2774,366,366,166,166,166,80};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
 ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[9] = 
   {0,0,3065,1383,473,166,166,166,80};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[9] = 
   {0,8420,2231,347,347,166,166,166,80};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
 ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[9] = 
   {209,209,209,198,187,176,165,165,85};
static const int ATL_tmmNT_SmLnk_XO[9] = 
   {221,221,221,221,188,177,166,166,97};
static const int ATL_tmmTN_SmLnk_XO[9] = 
   {199,199,199,199,199,188,177,177,85};
static const int ATL_tmmTT_SmLnk_XO[9] = 
   {461,461,461,461,461,461,461,461,461};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
 ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[9] = 
   {276,276,276,276,276,276,276,276,276};
static const int ATL_tmmNT_SnLmk_XO[9] = 
   {216,216,216,216,194,183,183,183,183};
static const int ATL_tmmTN_SnLmk_XO[9] = 
   {187,187,187,187,187,187,176,165,85};
static const int ATL_tmmTT_SnLmk_XO[9] = 
   {373,373,373,181,181,181,181,170,114};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
 ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[9] = 
   {176,176,176,176,176,165,165,165,85};
static const int ATL_tmmNT_SkLmn_XO[9] = 
   {0,299,299,198,198,198,176,165,85};
static const int ATL_tmmTN_SkLmn_XO[9] = 
   {0,198,198,198,198,187,176,165,85};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
 ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
