/* This file generated by /Users/whaley/TEST/ATLAS3.9.33.0/obj64sh/..//tune/blas/gemm/txover.c
*/
#ifndef ATL_TXOVER_H
#define ATL_TXOVER_H 1

#define ATL_PDIM 2
static const int ATL_tmmNN_SQmnk_XO[2] =
{144,188};
static const int ATL_tmmNT_SQmnk_XO[2] =
{148,209};
static const int ATL_tmmTN_SQmnk_XO[2] =
{146,311};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[18] =
{0,0,0,0,0,0,7112,0,5635,0,1694,0,0,1132,221,954,0,210};
static const int ATL_tmmNT_SmnLk_XO[18] =
{0,0,0,0,0,0,0,0,2432,0,2432,0,419,3279,254,520,72,226};
static const int ATL_tmmTN_SmnLk_XO[18] =
{0,0,0,0,0,0,0,0,7038,0,974,0,424,5206,261,1176,72,217};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[18] =
{0,0,0,0,0,0,0,0,0,2890,2890,0,422,1997,246,1416,0,168};
static const int ATL_tmmNT_SmkLn_XO[18] =
{0,0,0,0,0,0,0,0,5423,0,2084,2929,474,745,221,2033,101,546};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[18] =
{0,0,0,0,0,0,0,0,6883,0,1512,4659,0,507,232,584,72,149};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[18] =
{0,0,0,0,0,0,0,3511,0,3511,0,1349,435,864,226,595,104,420};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[18] =
{977,2389,977,3252,977,2469,865,1665,641,936,364,595,260,556,146,398,111,280};
static const int ATL_tmmNT_SmLnk_XO[18] =
{1030,2737,1030,3476,952,3441,719,1907,710,1703,608,1213,221,340,182,419,182,268};
static const int ATL_tmmTN_SmLnk_XO[18] =
{1182,2160,1182,3537,917,3101,847,1946,839,907,296,816,280,480,280,335,0,280};
static const int ATL_tmmTT_SmLnk_XO[18] =
{1228,2196,1228,3519,878,2158,878,1850,581,1413,410,889,289,700,153,496,118,164};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[18] =
{1429,3481,1116,3481,1116,3084,816,2601,562,842,453,1007,269,327,144,568,84,268};
static const int ATL_tmmNT_SnLmk_XO[18] =
{1234,2931,1091,3545,1091,3512,865,2176,563,1842,368,688,358,965,234,682,220,337};
static const int ATL_tmmTN_SnLmk_XO[18] =
{1482,2729,1133,1832,1061,2098,798,1339,674,910,409,560,259,887,144,305,122,152};
static const int ATL_tmmTT_SnLmk_XO[18] =
{1332,2694,1192,2886,1018,2340,1018,1311,0,999,336,612,336,410,243,309,243,268};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[18] =
{0,0,0,0,0,0,0,939,939,0,591,643,369,482,224,373,158,187};
static const int ATL_tmmNT_SkLmn_XO[18] =
{0,0,0,0,0,0,1296,0,983,0,0,465,0,322,0,245,96,268};
static const int ATL_tmmTN_SkLmn_XO[18] =
{0,0,0,0,0,0,1237,0,941,0,571,582,408,480,291,391,0,164};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
