/* This file generated by /home/whaley/TEST/ATLAS3.9.21.8/obj64/..//tune/blas/gemm/txover.c
 */
#ifndef ATL_TXOVER_H
   #define ATL_TXOVER_H 1

   #define ATL_PDIM 3
static const int ATL_tmmNN_SQmnk_XO[3] = 
   {107,107,214};
static const int ATL_tmmNT_SQmnk_XO[3] = 
   {107,107,214};
static const int ATL_tmmTN_SQmnk_XO[3] = 
   {107,107,214};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
 ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[27] = 
   {0,0,0,0,0,0,1900,3588,0,708,2349,0,229,1053,4000,112,361,1995,112,330,1100,0,52,105,0,52,0};
static const int ATL_tmmNT_SmnLk_XO[27] = 
   {0,0,0,0,0,0,1685,3175,0,701,1261,0,106,803,2660,106,255,1474,106,226,1069,52,60,190,0,52,0};
static const int ATL_tmmTN_SmnLk_XO[27] = 
   {0,0,0,0,0,0,1885,0,0,734,4377,0,233,1080,5172,113,228,2228,113,217,1376,0,52,109,0,52,0};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
 ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[27] = 
   {0,0,0,4840,0,0,1639,0,6000,1639,3003,4558,234,977,3148,114,388,968,106,227,713,52,94,121,0,52,57};
static const int ATL_tmmNT_SmkLn_XO[27] = 
   {0,0,0,2144,3889,0,2028,3845,0,1077,1874,0,230,1076,0,110,222,1145,110,209,725,52,59,109,0,52,57};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
 ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[27] = 
   {0,0,0,0,0,0,3467,0,0,773,0,0,208,1977,2976,137,234,1209,105,225,423,52,59,109,0,52,57};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[27] = 
   {0,0,0,2680,5896,0,2680,4432,0,429,2343,0,429,1367,2591,105,364,1439,105,224,702,0,52,294,0,0,52};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
 ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[27] = 
   {134,239,1100,134,359,1341,134,348,1190,134,293,643,112,221,613,112,197,309,112,121,236,52,104,128,52,56,128};
static const int ATL_tmmNT_SmLnk_XO[27] = 
   {142,248,0,127,359,1881,127,353,1095,127,336,686,127,232,628,112,187,355,112,121,236,52,105,113,52,58,105};
static const int ATL_tmmTN_SmLnk_XO[27] = 
   {163,248,1084,112,379,1600,112,356,795,112,260,643,112,221,613,112,123,294,112,121,236,52,105,113,52,59,113};
static const int ATL_tmmTT_SmLnk_XO[27] = 
   {171,245,0,171,391,1935,171,387,1195,141,350,658,112,237,613,112,126,339,112,121,236,52,104,128,52,58,105};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
 ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[27] = 
   {137,413,1826,137,504,1947,137,467,1473,104,344,696,104,203,636,104,150,606,104,136,436,52,105,105,52,56,128};
static const int ATL_tmmNT_SnLmk_XO[27] = 
   {121,242,1544,121,401,3393,121,398,1665,121,382,680,121,236,666,105,182,606,105,123,282,52,105,105,52,58,105};
static const int ATL_tmmTN_SnLmk_XO[27] = 
   {157,409,832,157,472,832,157,446,834,105,247,757,105,207,651,105,141,499,105,138,251,52,105,105,52,58,105};
static const int ATL_tmmTT_SnLmk_XO[27] = 
   {182,247,1016,182,390,2187,134,389,1190,134,344,696,105,228,636,105,129,499,105,138,251,52,105,105,52,58,105};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
 ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[27] = 
   {180,365,492,180,486,671,180,468,515,139,451,501,107,350,350,107,168,304,107,115,220,52,104,220,0,52,220};
static const int ATL_tmmNT_SkLmn_XO[27] = 
   {184,535,586,184,0,541,184,556,556,184,0,513,137,350,350,107,180,304,107,115,220,52,104,220,52,67,220};
static const int ATL_tmmTN_SkLmn_XO[27] = 
   {137,329,393,137,359,501,123,432,492,114,403,423,105,332,348,105,189,332,105,123,282,52,104,220,0,52,220};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
 ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
