/* This file generated by /Users/whaley/TEST/ATLAS3.9.33.0/obj64sh/..//tune/blas/gemm/txover.c
*/
#ifndef ATL_TXOVER_H
#define ATL_TXOVER_H 1

#define ATL_PDIM 2
static const int ATL_tmmNN_SQmnk_XO[2] =
{160,166};
static const int ATL_tmmNT_SQmnk_XO[2] =
{160,166};
static const int ATL_tmmTN_SQmnk_XO[2] =
{160,166};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[18] =
{0,0,0,0,0,0,4992,0,1790,0,0,538,172,1011,172,327,0,80};
static const int ATL_tmmNT_SmnLk_XO[18] =
{0,0,0,0,0,0,4741,0,0,1048,1048,3473,172,828,172,327,0,80};
static const int ATL_tmmTN_SmnLk_XO[18] =
{0,0,0,0,0,0,5437,0,1440,4574,440,2257,181,324,172,327,80,87};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[18] =
{0,0,0,0,0,7819,6557,0,1405,5291,464,2000,164,331,164,466,80,172};
static const int ATL_tmmNT_SmkLn_XO[18] =
{0,0,0,0,0,0,5329,0,0,879,405,650,160,405,160,345,99,187};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[18] =
{0,0,0,0,0,0,0,3913,1462,2076,567,2242,161,328,161,332,85,172};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[18] =
{0,0,0,0,0,0,0,7213,1709,3280,448,1235,165,363,165,408,85,172};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[18] =
{489,1019,435,768,435,1034,0,350,350,389,181,391,167,331,167,335,91,171};
static const int ATL_tmmNT_SmLnk_XO[18] =
{930,1721,930,2238,477,1209,429,775,249,815,191,335,171,325,161,329,85,171};
static const int ATL_tmmTN_SmLnk_XO[18] =
{0,462,462,959,0,462,462,874,314,575,254,371,254,320,171,325,80,186};
static const int ATL_tmmTT_SmLnk_XO[18] =
{599,1528,599,1841,590,1643,323,980,230,424,186,424,171,320,171,325,80,186};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[18] =
{678,2857,678,1923,678,2088,403,858,277,541,217,320,171,325,161,329,85,171};
static const int ATL_tmmNT_SnLmk_XO[18] =
{638,2688,502,2244,489,1256,380,717,249,430,224,386,224,327,224,324,96,171};
static const int ATL_tmmTN_SnLmk_XO[18] =
{525,538,525,1335,410,768,291,506,243,557,186,663,171,320,171,325,80,171};
static const int ATL_tmmTT_SnLmk_XO[18] =
{472,1160,472,1344,459,969,459,719,284,530,268,365,171,335,171,325,80,171};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[18] =
{0,448,0,448,435,475,0,318,246,451,0,200,0,200,171,171,80,186};
static const int ATL_tmmNT_SkLmn_XO[18] =
{0,514,0,473,0,473,0,446,0,347,0,200,0,171,171,171,80,171};
static const int ATL_tmmTN_SkLmn_XO[18] =
{0,405,0,405,405,459,316,325,0,253,164,268,0,164,164,191,85,171};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
