/* This file generated by /Users/whaley/TEST/ATLAS3.9.33.0/obj64sh/..//tune/blas/gemm/txover.c
 */
#ifndef ATL_TXOVER_H
   #define ATL_TXOVER_H 1

   #define ATL_PDIM 2
static const int ATL_tmmNN_SQmnk_XO[2] = 
   {107,140};
static const int ATL_tmmNT_SQmnk_XO[2] = 
   {0,111};
static const int ATL_tmmTN_SQmnk_XO[2] = 
   {111,111};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
 ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[18] = 
   {0,0,0,0,0,0,0,0,1420,0,248,1127,248,1307,129,190,52,74};
static const int ATL_tmmNT_SmnLk_XO[18] = 
   {0,0,0,0,0,0,0,0,0,0,582,2397,582,0,77,714,0,52};
static const int ATL_tmmTN_SmnLk_XO[18] = 
   {0,0,0,0,0,0,5606,0,5212,0,403,0,189,3121,58,876,52,80};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
 ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[18] = 
   {0,0,0,0,6000,0,3760,0,693,0,522,3235,293,346,69,121,52,63};
static const int ATL_tmmNT_SmkLn_XO[18] = 
   {0,0,0,0,0,0,0,0,1249,0,571,1084,149,365,77,190,52,69};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
 ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[18] = 
   {0,0,0,0,0,0,0,0,4530,5203,904,1256,0,531,57,806,52,57};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[18] = 
   {0,0,0,0,0,0,0,0,1340,4353,459,689,166,1013,63,144,52,57};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
 ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[18] = 
   {944,1700,837,1115,309,885,309,906,248,652,191,294,112,383,94,190,52,74};
static const int ATL_tmmNT_SmLnk_XO[18] = 
   {428,1822,428,1655,428,1402,347,1312,220,653,192,402,163,239,0,118,57,144};
static const int ATL_tmmTN_SmLnk_XO[18] = 
   {607,1779,403,1863,403,1442,403,1335,252,735,184,362,104,375,86,117,56,128};
static const int ATL_tmmTT_SmLnk_XO[18] = 
   {589,1547,589,1174,589,1467,589,893,268,780,185,381,140,335,75,136,75,128};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
 ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[18] = 
   {554,1953,554,1926,554,2078,383,1141,305,674,183,423,104,409,89,113,52,113};
static const int ATL_tmmNT_SnLmk_XO[18] = 
   {554,2814,554,2055,543,1407,543,760,298,534,176,628,112,383,94,190,52,97};
static const int ATL_tmmTN_SnLmk_XO[18] = 
   {611,1273,579,2441,439,1762,375,1185,208,553,197,343,164,354,79,204,67,113};
static const int ATL_tmmTT_SnLmk_XO[18] = 
   {505,1323,505,2033,505,1854,340,982,340,812,170,353,110,243,91,211,74,89};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
 ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[18] = 
   {489,3229,479,1370,420,657,420,507,0,275,186,394,138,195,0,105,52,128};
static const int ATL_tmmNT_SkLmn_XO[18] = 
   {0,457,457,0,0,444,444,1191,0,217,0,173,113,151,75,120,75,144};
static const int ATL_tmmTN_SkLmn_XO[18] = 
   {0,444,444,2885,435,1130,435,884,274,325,192,192,132,132,71,105,52,128};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
 ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
