/* This file generated by /Users/whaley/TEST/ATLAS3.9.33.0/obj64sh/..//tune/blas/gemm/txover.c
 */
#ifndef ATL_TXOVER_H
   #define ATL_TXOVER_H 1

   #define ATL_PDIM 2
static const int ATL_tmmNN_SQmnk_XO[2] = 
   {118,181};
static const int ATL_tmmNT_SQmnk_XO[2] = 
   {152,159};
static const int ATL_tmmTN_SQmnk_XO[2] = 
   {144,144};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
 ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[18] = 
   {0,0,0,0,0,0,0,0,0,0,1811,0,897,2977,160,893,56,63};
static const int ATL_tmmNT_SmnLk_XO[18] = 
   {0,0,0,0,7075,0,6150,0,6150,0,5427,0,517,4075,150,1458,63,118};
static const int ATL_tmmTN_SmnLk_XO[18] = 
   {0,0,0,0,0,0,0,0,0,0,2995,0,1379,7311,441,1007,56,79};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
 ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[18] = 
   {0,0,0,0,0,0,0,0,1547,0,1531,3461,805,6420,252,695,117,220};
static const int ATL_tmmNT_SmkLn_XO[18] = 
   {0,0,0,0,0,0,4844,0,4844,9838,0,4844,437,9614,141,1507,97,220};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
 ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[18] = 
   {0,0,0,0,0,0,0,0,0,0,2842,4938,612,2733,210,880,56,113};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[18] = 
   {0,0,0,0,0,0,2732,0,2732,0,0,1694,696,2744,224,779,145,375};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
 ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[18] = 
   {1232,2722,1232,2722,0,1232,551,2508,551,1295,0,551,225,514,173,345,116,217};
static const int ATL_tmmNT_SmLnk_XO[18] = 
   {1260,3491,823,2755,808,2511,808,2389,499,1497,433,861,355,509,181,599,105,113};
static const int ATL_tmmTN_SmLnk_XO[18] = 
   {1350,3149,1322,2318,765,2374,727,1529,727,1549,443,811,300,763,172,524,0,136};
static const int ATL_tmmTT_SmLnk_XO[18] = 
   {875,2627,862,2707,862,2780,579,1926,513,1113,440,841,284,756,153,300,105,252};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
 ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[18] = 
   {1032,2739,1032,2107,810,2768,698,2617,588,731,380,1058,224,855,160,573,0,102};
static const int ATL_tmmNT_SnLmk_XO[18] = 
   {926,2762,821,2753,806,2714,609,2311,511,1542,434,957,301,860,293,372,120,159};
static const int ATL_tmmTN_SnLmk_XO[18] = 
   {1246,2116,822,2342,680,1345,680,1180,541,1399,419,985,231,744,189,371,107,159};
static const int ATL_tmmTT_SnLmk_XO[18] = 
   {1181,2018,801,2750,801,979,645,2032,541,967,387,568,206,343,0,161,116,125};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
 ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[18] = 
   {0,0,0,0,1589,0,1589,0,1411,4883,506,0,318,430,0,133,87,182};
static const int ATL_tmmNT_SkLmn_XO[18] = 
   {0,0,0,0,5923,0,0,5923,1074,0,589,3277,192,472,153,205,102,148};
static const int ATL_tmmTN_SkLmn_XO[18] = 
   {0,0,0,0,5847,0,3556,0,956,0,447,0,268,569,184,295,0,148};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
 ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
