/* This file generated by /home/whaley/TEST/ATLAS3.9.21.8/obj64/..//tune/blas/gemm/txover.c
 */
#ifndef ATL_TXOVER_H
   #define ATL_TXOVER_H 1

   #define ATL_PDIM 3
static const int ATL_tmmNN_SQmnk_XO[3] = 
   {165,171,324};
static const int ATL_tmmNT_SQmnk_XO[3] = 
   {165,171,324};
static const int ATL_tmmTN_SQmnk_XO[3] = 
   {165,171,324};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
 ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[27] = 
   {0,0,0,0,0,0,0,0,0,1617,5705,0,1617,1845,0,390,390,4453,174,333,1029,174,332,977,0,80,5896};
static const int ATL_tmmNT_SmnLk_XO[27] = 
   {0,0,0,0,0,0,0,0,0,3832,4190,0,381,1511,0,381,568,4818,170,330,903,170,322,992,80,85,5896};
static const int ATL_tmmTN_SmnLk_XO[27] = 
   {0,0,0,0,0,0,0,0,0,3475,7329,0,1007,1856,0,349,529,4009,170,320,860,170,321,990,0,80,5892};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
 ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[27] = 
   {0,0,0,0,0,0,8346,8346,0,2945,3495,0,0,2945,5247,495,517,2781,171,328,678,171,325,641,80,92,360};
static const int ATL_tmmNT_SmkLn_XO[27] = 
   {0,0,0,0,0,0,0,0,0,3329,3537,0,0,3329,7412,0,536,2704,171,323,659,171,325,641,80,87,321};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
 ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[27] = 
   {0,0,0,0,0,0,0,0,0,0,5942,0,0,1625,5225,451,451,2398,173,320,1036,173,328,670,0,80,166};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[27] = 
   {0,0,0,0,0,0,0,8812,0,2403,4539,0,0,2403,8815,0,526,2704,171,325,880,171,325,641,0,80,166};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
 ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[27] = 
   {0,976,3017,976,976,3790,561,687,3462,401,497,2514,280,371,1188,163,222,925,163,196,345,163,191,334,80,170,322};
static const int ATL_tmmNT_SmLnk_XO[27] = 
   {632,848,3903,632,912,3903,632,858,3814,407,665,3315,274,361,1986,163,192,1096,163,184,333,163,175,334,80,170,322};
static const int ATL_tmmTN_SmLnk_XO[27] = 
   {609,770,3051,609,721,3809,609,609,1283,304,304,2221,243,273,1066,234,278,903,163,196,345,163,191,334,80,170,322};
static const int ATL_tmmTT_SmLnk_XO[27] = 
   {730,1038,3776,730,986,3858,730,846,3781,320,601,3031,243,285,1649,230,271,937,163,185,345,163,175,334,80,170,322};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
 ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[27] = 
   {605,1451,3891,0,605,3891,605,839,3812,400,654,2685,268,352,1895,163,206,1096,163,265,345,163,175,334,80,175,334};
static const int ATL_tmmNT_SnLmk_XO[27] = 
   {0,867,3913,867,867,3806,387,774,3935,258,611,2770,258,504,2221,242,282,937,176,271,356,163,175,334,80,175,334};
static const int ATL_tmmTN_SnLmk_XO[27] = 
   {556,1037,3022,0,556,2516,0,426,2776,270,482,1333,256,348,995,243,366,910,171,266,341,171,185,322,80,185,322};
static const int ATL_tmmTT_SnLmk_XO[27] = 
   {797,1007,3804,797,797,3804,597,675,3072,322,382,2583,246,291,1178,232,272,928,166,261,336,166,179,345,80,175,334};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
 ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[27] = 
   {0,0,1126,0,0,1126,0,1126,0,0,758,0,0,409,0,171,181,512,0,171,341,171,185,322,80,185,322};
static const int ATL_tmmNT_SkLmn_XO[27] = 
   {0,1293,3604,0,0,1055,0,0,1055,0,614,625,0,452,546,171,184,386,0,171,353,171,185,322,80,185,322};
static const int ATL_tmmTN_SkLmn_XO[27] = 
   {0,0,1138,0,0,1138,0,1138,1568,0,914,0,0,376,0,0,195,364,171,190,330,171,185,322,80,170,322};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
 ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
