/* This file generated by /home/whaley/TEST/ATLAS3.9.38.1/obj64/..//tune/blas/gemm/txover.c
 */
#ifndef ATL_TXOVER_H
   #define ATL_TXOVER_H 1

   #define ATL_PDIM 2
static const int ATL_tmmNN_SQmnk_XO[2] = 
   {0,100};
static const int ATL_tmmNT_SQmnk_XO[2] = 
   {0,107};
static const int ATL_tmmTN_SQmnk_XO[2] = 
   {81,107};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
 ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[18] = 
   {0,0,0,0,0,0,4284,5696,0,1590,708,1196,190,574,0,63,0,40};
static const int ATL_tmmNT_SmnLk_XO[18] = 
   {0,0,0,0,0,0,3860,4688,1377,1377,787,2313,257,272,40,71,40,47};
static const int ATL_tmmTN_SmnLk_XO[18] = 
   {0,0,0,0,7308,7679,1749,5391,636,1053,193,453,176,282,40,68,0,40};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
 ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[18] = 
   {0,0,0,0,7418,9244,1942,3956,1942,1942,517,847,187,288,87,87,40,82};
static const int ATL_tmmNT_SmkLn_XO[18] = 
   {0,0,0,0,0,0,0,4074,2099,0,637,637,209,593,0,82,40,44};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
 ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[18] = 
   {0,0,0,0,6610,0,3220,0,961,2821,329,816,154,394,75,87,0,40};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[18] = 
   {0,0,0,0,0,0,5405,5862,0,2212,597,792,169,290,48,107,40,44};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
 ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[18] = 
   {416,786,405,764,405,479,244,313,235,331,0,161,139,166,0,97,51,86};
static const int ATL_tmmNT_SmLnk_XO[18] = 
   {0,461,0,461,374,434,244,344,244,287,174,332,138,167,110,257,61,97};
static const int ATL_tmmTN_SmLnk_XO[18] = 
   {467,520,467,467,266,1004,266,343,0,266,188,252,150,160,80,85,45,86};
static const int ATL_tmmTT_SmLnk_XO[18] = 
   {356,455,356,444,356,474,238,455,207,300,153,276,81,168,76,3118,53,3485};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
 ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[18] = 
   {0,470,438,733,371,501,313,421,230,365,150,263,150,160,80,0,57,0};
static const int ATL_tmmNT_SnLmk_XO[18] = 
   {0,430,430,536,349,448,316,421,184,393,155,325,131,0,85,0,68,0};
static const int ATL_tmmTN_SnLmk_XO[18] = 
   {473,516,473,1097,372,451,272,306,239,335,165,0,85,0,62,0,57,0};
static const int ATL_tmmTT_SnLmk_XO[18] = 
   {468,572,454,465,422,458,268,384,216,281,133,183,103,0,80,0,57,6000};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
 ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[18] = 
   {0,482,0,482,406,419,320,415,248,263,150,246,108,0,62,0,57,0};
static const int ATL_tmmNT_SkLmn_XO[18] = 
   {437,555,437,508,320,474,320,332,243,346,141,192,124,139,82,177,51,0};
static const int ATL_tmmTN_SkLmn_XO[18] = 
   {0,480,480,595,411,439,329,329,206,1633,149,251,149,0,0,80,57,0};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
 ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
