/* This file generated by /home/whaley/TEST/ATLAS3.9.39.0/obj64/..//tune/blas/gemm/txover.c
*/
#ifndef ATL_TXOVER_H
#define ATL_TXOVER_H 1

#define ATL_PDIM 2
static const int ATL_tmmNN_SQmnk_XO[2] =
{160,166};
static const int ATL_tmmNT_SQmnk_XO[2] =
{160,166};
static const int ATL_tmmTN_SQmnk_XO[2] =
{160,166};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[18] =
{0,0,0,0,6563,0,0,2253,338,553,172,324,172,324,172,327,0,80};
static const int ATL_tmmNT_SmnLk_XO[18] =
{0,6337,0,6337,6337,6337,0,2401,689,750,267,324,172,324,172,327,0,80};
static const int ATL_tmmTN_SmnLk_XO[18] =
{0,0,0,0,2853,5482,676,1180,172,752,172,324,172,324,172,327,0,80};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[18] =
{0,2124,0,2124,0,1403,0,964,481,568,172,324,172,324,172,327,80,172};
static const int ATL_tmmNT_SmkLn_XO[18] =
{5450,5450,0,2901,0,2173,0,965,320,568,172,324,172,324,172,327,80,172};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[18] =
{0,0,0,0,0,0,856,1476,196,706,172,324,172,324,172,327,80,172};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[18] =
{0,0,0,0,0,0,0,1867,490,874,172,324,172,324,172,327,80,172};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[18] =
{0,322,0,322,0,322,219,364,186,2204,171,320,171,320,171,0,80,0};
static const int ATL_tmmNT_SmLnk_XO[18] =
{0,387,0,387,387,526,280,365,171,320,171,320,171,0,171,0,80,0};
static const int ATL_tmmTN_SmLnk_XO[18] =
{323,451,0,323,0,323,280,365,171,320,171,320,171,0,171,0,80,0};
static const int ATL_tmmTT_SmLnk_XO[18] =
{401,471,401,609,308,374,243,332,214,327,163,327,163,0,163,0,87,0};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[18] =
{433,446,0,433,377,410,280,358,180,320,171,320,171,320,171,4000,80,0};
static const int ATL_tmmNT_SnLmk_XO[18] =
{0,384,0,384,384,1239,280,372,163,327,163,327,163,327,163,0,87,0};
static const int ATL_tmmTN_SnLmk_XO[18] =
{377,461,0,377,377,410,280,372,163,327,163,327,163,0,163,0,87,0};
static const int ATL_tmmTT_SnLmk_XO[18] =
{353,453,339,528,313,372,255,327,255,327,163,327,163,0,163,0,87,0};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[18] =
{178,430,178,326,178,222,0,178,178,185,171,185,0,171,171,0,80,0};
static const int ATL_tmmNT_SkLmn_XO[18] =
{185,333,185,333,185,229,185,185,171,185,0,171,171,0,171,0,80,0};
static const int ATL_tmmTN_SkLmn_XO[18] =
{196,328,196,240,196,274,0,185,171,185,0,171,171,0,171,0,80,0};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
