/* This file generated by /home/whaley/TEST/ATLAS3.9.39.0/obj64/..//tune/blas/gemm/txover.c
 */
#ifndef ATL_TXOVER_H
   #define ATL_TXOVER_H 1

   #define ATL_PDIM 2
static const int ATL_tmmNN_SQmnk_XO[2] = 
   {65,0};
static const int ATL_tmmNT_SQmnk_XO[2] = 
   {95,0};
static const int ATL_tmmTN_SQmnk_XO[2] = 
   {65,0};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
 ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[18] = 
   {0,0,0,0,0,0,0,1710,337,479,214,384,45,74,0,28,28,0};
static const int ATL_tmmNT_SmnLk_XO[18] = 
   {0,0,0,0,0,0,1858,0,574,696,209,389,51,105,28,35,28,0};
static const int ATL_tmmTN_SmnLk_XO[18] = 
   {0,0,6000,0,1979,5128,930,1017,229,338,145,430,35,91,0,28,28,0};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
 ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[18] = 
   {0,2947,0,2947,0,2947,1560,1621,339,647,339,423,40,79,0,28,28,0};
static const int ATL_tmmNT_SmkLn_XO[18] = 
   {3879,4011,3879,4475,3879,5507,1502,2487,237,518,237,307,28,62,28,33,28,0};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
 ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[18] = 
   {0,0,1795,3173,1795,3369,571,929,167,488,109,390,0,91,28,33,0,28};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[18] = 
   {0,0,0,4575,0,4575,1660,1660,245,649,245,377,28,62,28,33,28,0};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
 ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[18] = 
   {235,307,235,268,224,308,174,208,118,184,109,0,64,0,42,0,35,0};
static const int ATL_tmmNT_SmLnk_XO[18] = 
   {246,333,246,318,246,291,172,249,113,147,102,0,57,0,42,0,35,0};
static const int ATL_tmmTN_SmLnk_XO[18] = 
   {264,307,264,309,237,282,163,229,124,192,102,0,72,0,42,0,35,0};
static const int ATL_tmmTT_SmLnk_XO[18] = 
   {235,307,235,322,235,310,160,245,109,187,64,0,49,0,42,0,35,0};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
 ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[18] = 
   {286,329,286,296,223,246,156,213,123,180,105,117,72,0,42,0,35,0};
static const int ATL_tmmNT_SnLmk_XO[18] = 
   {256,314,256,285,256,313,133,298,133,178,118,0,57,0,42,0,35,0};
static const int ATL_tmmTN_SnLmk_XO[18] = 
   {219,381,219,278,219,323,158,192,102,194,72,0,57,0,42,0,35,0};
static const int ATL_tmmTT_SnLmk_XO[18] = 
   {0,297,297,363,232,316,183,202,127,193,118,0,57,0,42,0,35,0};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
 ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[18] = 
   {178,267,178,192,178,192,178,0,148,0,118,0,57,0,42,0,35,0};
static const int ATL_tmmNT_SkLmn_XO[18] = 
   {183,257,183,213,153,232,127,184,109,139,109,0,64,0,42,0,35,0};
static const int ATL_tmmTN_SkLmn_XO[18] = 
   {269,283,0,269,226,236,162,0,117,0,102,0,72,0,42,0,35,0};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
 ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
