/* This file generated by /home/whaley/TEST/ATLAS3.9.38.1/obj64/..//tune/blas/gemm/txover.c
*/
#ifndef ATL_TXOVER_H
#define ATL_TXOVER_H 1

#define ATL_PDIM 2
static const int ATL_tmmNN_SQmnk_XO[2] =
{169,169};
static const int ATL_tmmNT_SQmnk_XO[2] =
{169,169};
static const int ATL_tmmTN_SQmnk_XO[2] =
{169,169};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[18] =
{0,0,0,0,0,0,3800,3800,0,1751,663,2740,173,340,173,346,0,84};
static const int ATL_tmmNT_SmnLk_XO[18] =
{0,0,0,0,0,0,0,3502,1876,0,571,591,275,356,173,346,0,84};
static const int ATL_tmmTN_SmnLk_XO[18] =
{0,0,0,0,4177,6823,1531,1662,471,956,181,822,181,343,181,344,0,84};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[18] =
{0,0,0,0,0,0,1947,4211,0,1947,544,687,181,343,181,344,84,170};
static const int ATL_tmmNT_SmkLn_XO[18] =
{0,0,0,0,0,0,5271,5593,2166,2166,0,630,181,381,181,344,84,170};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[18] =
{0,0,0,0,7357,0,4714,4912,698,2502,684,1158,181,353,181,344,84,189};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[18] =
{0,0,0,0,0,0,0,3991,0,1261,521,841,181,343,181,344,84,170};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[18] =
{0,472,472,565,379,740,379,3227,276,336,178,336,178,336,178,337,84,176};
static const int ATL_tmmNT_SmLnk_XO[18] =
{473,548,473,503,349,541,286,370,178,359,178,336,178,336,178,337,84,176};
static const int ATL_tmmTN_SmLnk_XO[18] =
{648,956,300,522,300,613,243,368,187,356,187,336,178,336,178,337,84,176};
static const int ATL_tmmTT_SmLnk_XO[18] =
{372,470,372,511,266,635,266,366,266,336,178,336,178,336,178,337,84,176};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[18] =
{504,857,504,585,456,578,335,657,290,370,189,552,178,336,178,337,84,176};
static const int ATL_tmmNT_SnLmk_XO[18] =
{0,502,502,1865,459,3249,323,542,263,339,238,370,178,336,178,337,84,176};
static const int ATL_tmmTN_SnLmk_XO[18] =
{651,1069,512,779,409,592,315,534,254,483,178,347,178,336,178,337,84,176};
static const int ATL_tmmTT_SnLmk_XO[18] =
{541,629,512,534,358,542,332,654,286,370,178,336,178,336,178,337,84,176};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[18] =
{474,570,474,549,474,504,0,350,284,317,284,369,176,198,176,176,84,176};
static const int ATL_tmmNT_SkLmn_XO[18] =
{461,514,461,644,461,511,312,502,198,209,0,198,0,176,176,176,84,176};
static const int ATL_tmmTN_SkLmn_XO[18] =
{404,534,0,404,404,481,327,411,0,278,176,198,0,176,176,176,84,176};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
