/* This file generated by /home/whaley/TEST/ATLAS3.9.38.1/obj64/..//tune/blas/gemm/txover.c
 */
#ifndef ATL_TXOVER_H
   #define ATL_TXOVER_H 1

   #define ATL_PDIM 2
static const int ATL_tmmNN_SQmnk_XO[2] = 
   {125,0};
static const int ATL_tmmNT_SQmnk_XO[2] = 
   {125,0};
static const int ATL_tmmTN_SQmnk_XO[2] = 
   {125,0};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
 ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[18] = 
   {0,0,0,4000,1366,0,0,1366,489,808,129,385,129,244,0,60,60,0};
static const int ATL_tmmNT_SmnLk_XO[18] = 
   {2903,0,1660,2821,0,1642,0,1642,0,451,215,246,125,321,0,60,0,60};
static const int ATL_tmmTN_SmnLk_XO[18] = 
   {0,0,3890,5672,2504,4216,565,921,210,563,129,277,129,245,0,60,60,0};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
 ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[18] = 
   {0,2142,2142,3177,2074,4993,1401,1825,129,884,129,345,129,245,60,140,60,0};
static const int ATL_tmmNT_SmkLn_XO[18] = 
   {4258,0,2517,3167,1684,3147,1197,3304,437,1710,129,243,129,245,60,129,60,0};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
 ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[18] = 
   {0,0,3970,0,1362,1921,646,680,326,873,129,323,129,245,60,129,60,0};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[18] = 
   {5870,0,0,5870,1844,5782,1361,1786,607,1054,0,323,129,245,60,129,60,0};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
 ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[18] = 
   {229,714,229,743,229,701,214,257,121,242,121,0,121,0,60,0,60,0};
static const int ATL_tmmNT_SmLnk_XO[18] = 
   {213,242,213,1188,213,329,197,257,121,242,121,0,121,0,60,0,60,0};
static const int ATL_tmmTN_SmLnk_XO[18] = 
   {152,242,152,392,136,528,136,241,136,0,121,0,121,0,60,0,60,0};
static const int ATL_tmmTT_SmLnk_XO[18] = 
   {234,263,234,1193,219,455,204,249,129,249,129,249,129,244,60,0,60,0};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
 ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[18] = 
   {374,1619,0,374,181,256,136,241,136,241,136,0,121,0,60,0,0,60};
static const int ATL_tmmNT_SnLmk_XO[18] = 
   {238,1648,238,293,220,242,198,620,121,242,121,242,121,0,60,0,60,0};
static const int ATL_tmmTN_SnLmk_XO[18] = 
   {227,712,227,343,211,271,136,256,136,0,136,0,121,0,60,0,60,0};
static const int ATL_tmmTT_SnLmk_XO[18] = 
   {317,2472,240,284,196,269,196,242,121,242,121,0,121,0,60,0,60,0};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
 ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[18] = 
   {239,253,239,401,130,196,121,151,121,136,0,121,121,0,60,0,60,0};
static const int ATL_tmmNT_SkLmn_XO[18] = 
   {154,169,154,229,154,211,136,181,136,0,121,0,121,0,60,0,60,0};
static const int ATL_tmmTN_SkLmn_XO[18] = 
   {258,330,0,258,199,226,121,136,121,136,0,121,121,0,60,0,60,0};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
 ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
