/* This file generated by /home/whaley/TEST/ATLAS3.9.39.0/obj64/..//tune/blas/gemm/txover.c
*/
#ifndef ATL_TXOVER_H
#define ATL_TXOVER_H 1

#define ATL_PDIM 2
static const int ATL_tmmNN_SQmnk_XO[2] =
{160,166};
static const int ATL_tmmNT_SQmnk_XO[2] =
{160,166};
static const int ATL_tmmTN_SQmnk_XO[2] =
{160,166};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[18] =
{0,0,0,0,0,0,7906,8000,2024,2899,747,893,276,324,172,327,80,87};
static const int ATL_tmmNT_SmnLk_XO[18] =
{0,0,0,0,0,0,7730,0,2262,2262,656,1220,218,323,218,327,80,87};
static const int ATL_tmmTN_SmnLk_XO[18] =
{0,0,0,0,0,0,6071,8503,2020,2974,535,879,170,332,170,321,0,80};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[18] =
{0,0,0,0,0,0,0,5414,2476,3077,674,786,274,323,170,321,80,166};
static const int ATL_tmmNT_SmkLn_XO[18] =
{0,0,0,0,0,0,4879,5627,2637,3087,687,887,179,323,170,321,80,166};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[18] =
{0,0,0,0,0,0,4630,0,0,1516,304,956,170,323,170,321,80,166};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[18] =
{0,0,0,0,0,0,6600,7125,2335,2456,534,898,170,323,170,321,80,166};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[18] =
{533,724,533,554,533,684,400,456,278,445,255,330,160,330,160,326,85,0};
static const int ATL_tmmNT_SmLnk_XO[18] =
{575,818,0,575,575,729,402,428,295,396,262,342,160,330,160,326,85,0};
static const int ATL_tmmTN_SmLnk_XO[18] =
{540,667,540,561,540,697,403,519,365,449,259,329,170,329,170,322,80,160};
static const int ATL_tmmTT_SmLnk_XO[18] =
{581,665,0,581,581,720,404,443,288,493,259,329,170,329,170,322,80,160};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[18] =
{541,934,541,892,541,692,409,469,280,387,265,340,170,329,170,322,80,160};
static const int ATL_tmmNT_SnLmk_XO[18] =
{537,781,537,568,537,688,405,472,294,499,265,340,170,329,170,322,80,172};
static const int ATL_tmmTN_SnLmk_XO[18] =
{533,926,533,618,533,684,401,523,279,499,265,340,170,329,170,322,80,160};
static const int ATL_tmmTT_SnLmk_XO[18] =
{569,865,569,579,569,707,413,520,276,455,265,340,170,329,170,322,80,172};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[18] =
{0,537,0,537,537,692,0,362,285,3220,0,262,160,193,160,160,80,160};
static const int ATL_tmmNT_SkLmn_XO[18] =
{0,578,0,526,526,766,287,431,240,368,222,284,160,182,160,160,80,160};
static const int ATL_tmmTN_SkLmn_XO[18] =
{0,545,0,545,545,784,403,1024,289,374,0,205,160,193,160,160,80,160};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
