/* This file generated by /home/whaley/TEST/ATLAS3.9.38.1/obj64/..//tune/blas/gemm/txover.c
*/
#ifndef ATL_TXOVER_H
#define ATL_TXOVER_H 1

#define ATL_PDIM 2
static const int ATL_tmmNN_SQmnk_XO[2] =
{169,169};
static const int ATL_tmmNT_SQmnk_XO[2] =
{169,169};
static const int ATL_tmmTN_SQmnk_XO[2] =
{169,169};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[18] =
{0,0,7014,0,3149,4066,808,1425,173,738,173,340,173,340,173,346,0,84};
static const int ATL_tmmNT_SmnLk_XO[18] =
{6119,0,5135,0,3301,4289,340,1805,340,340,173,340,173,340,173,346,0,84};
static const int ATL_tmmTN_SmnLk_XO[18] =
{0,0,5365,7349,2060,4763,329,1425,173,554,173,340,173,340,173,346,84,0};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[18] =
{2709,3604,2015,2167,1087,3139,1087,2335,287,356,173,340,173,340,173,346,84,176};
static const int ATL_tmmNT_SmkLn_XO[18] =
{0,3824,2433,2433,875,2984,173,1242,173,569,173,340,173,340,173,346,84,176};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[18] =
{0,0,4660,8000,1107,2463,618,2251,173,371,173,340,173,340,173,346,84,176};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[18] =
{0,0,0,4512,4512,5317,1643,1665,279,936,173,340,173,340,173,346,84,176};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[18] =
{180,671,180,373,180,343,180,343,180,343,180,343,180,343,180,343,84,175};
static const int ATL_tmmNT_SmLnk_XO[18] =
{209,341,209,389,197,448,181,344,181,344,181,344,181,344,181,2164,84,175};
static const int ATL_tmmTN_SmLnk_XO[18] =
{292,349,292,384,175,339,175,339,175,339,175,339,175,339,175,0,84,0};
static const int ATL_tmmTT_SmLnk_XO[18] =
{253,340,253,384,175,339,175,339,175,339,175,0,175,0,175,0,84,0};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[18] =
{321,449,321,363,321,432,180,343,180,343,180,343,180,0,180,343,84,0};
static const int ATL_tmmNT_SnLmk_XO[18] =
{384,398,384,474,271,343,180,343,180,343,180,343,180,343,180,343,84,0};
static const int ATL_tmmTN_SnLmk_XO[18] =
{361,543,267,383,267,339,175,339,175,339,175,339,175,339,175,0,84,0};
static const int ATL_tmmTT_SnLmk_XO[18] =
{333,535,320,398,190,343,180,343,180,343,180,343,180,343,180,343,84,0};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[18] =
{0,193,0,193,193,249,175,189,0,175,0,175,175,0,175,0,84,0};
static const int ATL_tmmNT_SkLmn_XO[18] =
{189,203,0,189,189,189,175,189,0,175,0,175,175,0,175,0,84,0};
static const int ATL_tmmTN_SkLmn_XO[18] =
{0,189,0,189,189,204,175,189,0,175,0,175,175,0,175,0,84,0};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
