/* This file generated by /home/whaley/TEST/ATLAS3.9.33.1/obj64/..//tune/blas/gemm/txover.c
*/
#ifndef ATL_TXOVER_H
#define ATL_TXOVER_H 1

#define ATL_PDIM 1
static const int ATL_tmmNN_SQmnk_XO[1] =
{115};
static const int ATL_tmmNT_SQmnk_XO[1] =
{115};
static const int ATL_tmmTN_SQmnk_XO[1] =
{115};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[9] =
{4222,4222,4222,4222,4222,4222,202,63,56};
static const int ATL_tmmNT_SmnLk_XO[9] =
{0,4222,4222,4222,4222,202,187,63,56};
static const int ATL_tmmTN_SmnLk_XO[9] =
{0,5913,5913,5412,5412,214,176,60,56};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[9] =
{0,0,561,257,238,219,142,65,56};
static const int ATL_tmmNT_SmkLn_XO[9] =
{2764,2764,2764,2764,251,175,137,60,56};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[9] =
{0,0,4339,1950,571,375,375,375,56};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[9] =
{2622,2622,2622,2622,2622,2622,2622,60,56};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[9] =
{224,224,224,224,202,169,112,66,61};
static const int ATL_tmmNT_SmLnk_XO[9] =
{282,282,282,282,226,215,112,66,61};
static const int ATL_tmmTN_SmLnk_XO[9] =
{453,453,421,378,367,174,118,72,61};
static const int ATL_tmmTT_SmLnk_XO[9] =
{196,196,196,196,185,174,118,72,61};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[9] =
{307,307,307,307,307,307,112,66,61};
static const int ATL_tmmNT_SnLmk_XO[9] =
{236,236,236,236,225,169,112,66,61};
static const int ATL_tmmTN_SnLmk_XO[9] =
{343,343,343,343,332,186,175,72,61};
static const int ATL_tmmTT_SnLmk_XO[9] =
{812,812,373,296,285,263,252,252,252};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[9] =
{320,320,320,287,220,220,220,164,61};
static const int ATL_tmmNT_SkLmn_XO[9] =
{292,292,292,281,180,169,112,66,61};
static const int ATL_tmmTN_SkLmn_XO[9] =
{286,286,286,286,196,174,129,118,61};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
