/* This file generated by /home/whaley/TEST/ATLAS3.9.33.1/obj64/..//tune/blas/gemm/txover.c
 */
#ifndef ATL_TXOVER_H
   #define ATL_TXOVER_H 1

   #define ATL_PDIM 1
static const int ATL_tmmNN_SQmnk_XO[1] = 
   {85};
static const int ATL_tmmNT_SQmnk_XO[1] = 
   {85};
static const int ATL_tmmTN_SQmnk_XO[1] = 
   {107};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
 ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[9] = 
   {0,1386,1386,515,283,85,85,40,40};
static const int ATL_tmmNT_SmnLk_XO[9] = 
   {0,2134,2134,268,268,85,85,40,40};
static const int ATL_tmmTN_SmnLk_XO[9] = 
   {0,0,0,1646,1646,166,144,40,40};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
 ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[9] = 
   {0,0,251,251,160,80,80,40,40};
static const int ATL_tmmNT_SmkLn_XO[9] = 
   {1405,1405,265,265,80,80,80,40,40};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
 ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[9] = 
   {0,1410,755,465,465,85,85,45,40};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[9] = 
   {0,0,0,0,160,80,80,40,40};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
 ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[9] = 
   {451,451,451,451,451,438,438,54,47};
static const int ATL_tmmNT_SmLnk_XO[9] = 
   {121,121,121,106,106,106,84,47,40};
static const int ATL_tmmTN_SmLnk_XO[9] = 
   {167,167,167,167,91,84,84,47,40};
static const int ATL_tmmTT_SmLnk_XO[9] = 
   {91,91,91,91,84,84,84,47,40};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
 ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[9] = 
   {204,204,204,204,204,129,84,47,40};
static const int ATL_tmmNT_SnLmk_XO[9] = 
   {343,343,343,343,343,84,84,47,40};
static const int ATL_tmmTN_SnLmk_XO[9] = 
   {181,181,181,121,106,106,84,47,40};
static const int ATL_tmmTT_SnLmk_XO[9] = 
   {249,249,249,235,99,84,84,47,40};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
 ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[9] = 
   {0,0,144,129,129,84,84,47,47};
static const int ATL_tmmNT_SkLmn_XO[9] = 
   {151,151,136,121,106,84,84,47,47};
static const int ATL_tmmTN_SkLmn_XO[9] = 
   {152,152,152,152,91,84,84,47,47};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
 ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
