/* This file generated by /home/whaley/TEST/ATLAS3.9.33.1/obj64/..//tune/blas/gemm/txover.c
*/
#ifndef ATL_TXOVER_H
#define ATL_TXOVER_H 1

#define ATL_PDIM 1
static const int ATL_tmmNN_SQmnk_XO[1] =
{166};
static const int ATL_tmmNT_SQmnk_XO[1] =
{166};
static const int ATL_tmmTN_SQmnk_XO[1] =
{166};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[9] =
{2949,2949,1123,477,172,172,172,172,80};
static const int ATL_tmmNT_SmnLk_XO[9] =
{0,0,1093,477,172,172,172,172,80};
static const int ATL_tmmTN_SmnLk_XO[9] =
{0,4325,1280,522,172,172,172,172,80};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[9] =
{0,0,645,645,172,172,172,172,80};
static const int ATL_tmmNT_SmkLn_XO[9] =
{1516,1516,590,590,590,590,590,590,80};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[9] =
{0,1980,1120,538,172,172,172,172,80};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[9] =
{0,0,0,507,172,172,172,172,80};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[9] =
{424,424,424,424,171,171,171,171,80};
static const int ATL_tmmNT_SmLnk_XO[9] =
{177,177,177,177,177,177,177,163,87};
static const int ATL_tmmTN_SmLnk_XO[9] =
{245,245,245,245,171,171,171,171,80};
static const int ATL_tmmTT_SmLnk_XO[9] =
{185,185,185,185,185,171,171,171,80};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[9] =
{171,171,171,171,171,171,171,171,80};
static const int ATL_tmmNT_SnLmk_XO[9] =
{0,0,0,0,0,0,0,0,0};
static const int ATL_tmmTN_SnLmk_XO[9] =
{1157,1157,1157,1157,171,171,171,171,80};
static const int ATL_tmmTT_SnLmk_XO[9] =
{199,199,199,185,171,171,171,171,80};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[9] =
{354,340,340,340,340,340,340,340,80};
static const int ATL_tmmNT_SkLmn_XO[9] =
{171,171,171,171,171,171,171,171,80};
static const int ATL_tmmTN_SkLmn_XO[9] =
{171,171,171,171,171,171,171,171,80};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
