/* This file generated by /home/whaley/TEST/ATLAS3.9.33.1/obj64/..//tune/blas/gemm/txover.c
 */
#ifndef ATL_TXOVER_H
   #define ATL_TXOVER_H 1

   #define ATL_PDIM 1
static const int ATL_tmmNN_SQmnk_XO[1] = 
   {107};
static const int ATL_tmmNT_SQmnk_XO[1] = 
   {107};
static const int ATL_tmmTN_SQmnk_XO[1] = 
   {167};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
 ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[9] = 
   {5483,2804,1072,1072,1072,1072,1072,47,40};
static const int ATL_tmmNT_SmnLk_XO[9] = 
   {0,0,0,0,3193,310,310,47,40};
static const int ATL_tmmTN_SmnLk_XO[9] = 
   {0,0,0,0,0,0,0,82,40};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
 ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[9] = 
   {0,0,0,326,250,174,155,117,40};
static const int ATL_tmmNT_SmkLn_XO[9] = 
   {997,997,997,397,245,169,160,44,40};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
 ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[9] = 
   {0,8467,3460,1546,489,163,135,58,44};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[9] = 
   {5814,1629,1629,1629,519,519,519,204,40};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
 ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[9] = 
   {694,694,694,306,216,160,149,149,45};
static const int ATL_tmmNT_SmLnk_XO[9] = 
   {534,534,534,534,534,158,136,102,45};
static const int ATL_tmmTN_SmLnk_XO[9] = 
   {763,404,404,248,169,147,136,102,45};
static const int ATL_tmmTT_SmLnk_XO[9] = 
   {264,264,264,264,253,242,242,242,45};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
 ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[9] = 
   {364,364,364,309,254,198,142,62,57};
static const int ATL_tmmNT_SnLmk_XO[9] = 
   {541,354,354,288,277,175,142,85,45};
static const int ATL_tmmTN_SnLmk_XO[9] = 
   {540,519,519,519,519,519,142,85,45};
static const int ATL_tmmTT_SnLmk_XO[9] = 
   {617,617,522,242,220,198,142,85,45};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
 ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[9] = 
   {288,277,277,277,175,153,96,73,45};
static const int ATL_tmmNT_SkLmn_XO[9] = 
   {461,271,271,260,158,136,114,68,40};
static const int ATL_tmmTN_SkLmn_XO[9] = 
   {834,834,834,834,834,834,84,79,45};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
 ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
