/* generated by ATLAS/tune/sysinfo/cachesrch.c */
#ifndef ATLAS_CACHE_H
   #define ATLAS_CACHE_H 1

#define L1C_SZ 32768
#ifdef SREAL
   #define L1C_ELTS 8192
#elif defined(DREAL) || defined(SCPLX)
   #define L1C_ELTS 4096
#elif defined(DCPLX)
   #define L1C_ELTS 2048
#endif

#define L2C_SZ 524288
#ifdef SREAL
   #define L2C_ELTS 131072
#elif defined(DREAL) || defined(SCPLX)
   #define L2C_ELTS 65536
#elif defined(DCPLX)
   #define L2C_ELTS 32768
#endif

#define LLPC_LVL 1
#define LLPC_SZ  L1C_SZ
#define LLPC_ELTS  L1C_ELTS
#define LLC_LVL 2
#define LLC_SZ  L2C_SZ
#define LLC_ELTS  L2C_ELTS

#endif /* end multiple inclusion guard */
