.. math-atlas
.. _math-atlas: http://math-atlas.sourceforge.net
.. _`math-atlas github`: http://github.com/math-atlas/math-atlas

.. _`math-atlas mailing list`: http://sourceforge.net/mailarchive/forum.php?forum_name=math-atlas-devel
.. _`math-atlas patch tracker`: http://sourceforge.net/tracker/?group_id=23725&atid=379484
.. _`math-atlas home page`: http://math-atlas.sourceforge.net/
.. _`math-atlas home page`: http://math-atlas.sourceforge.net/
.. _`math-atlas developer home page`: http://math-atlas.sourceforge.net/devel/
.. _`atlas-contrib`: http://math-atlas.sourceforge.net/devel/atlas_contrib/
.. _`atlas-devel`: http://math-atlas.sourceforge.net/devel/atlas_devel/
.. _`atlas-docs`: http://math-atlas.sourceforge.net/faq.html#doc
