/* generated by ATLAS/tune/sysinfo/cacheInfo_x86.c */
#ifndef ATLAS_CACHE_H
   #define ATLAS_CACHE_H 1
#define x86_NHYPTHR 1 /* hyperthreading number */
#define x86_NCORPAK 32 /* ncores per package */

#define L1C_SZ 32768L
#define L1C_LS 64
#define L1C_NSET 64
#define L1C_NWAY 8
#define L1C_INCLUSIVE 1
#define L1C_NSHARE 1
#define L1C_SURE 1
#ifdef SREAL
   #define L1C_ELTS 8192
   #define L1C_LSELTS 16
#elif defined(DREAL) || defined(SCPLX)
   #define L1C_ELTS 4096
   #define L1C_LSELTS 8
#elif defined(DCPLX)
   #define L1C_ELTS 2048
   #define L1C_LSELTS 4
#endif

#define L1C_SZ 32768L
#define L1C_LS 64
#define L1C_NSET 64
#define L1C_NWAY 8
#define L1C_NSHARE 1
#define L1C_SURE 1
#ifdef SREAL
   #define L1C_ELTS 8192L
   #define L1C_LSELTS 16
#elif defined(DREAL) || defined(SCPLX)
   #define L1C_ELTS 4096L
   #define L1C_LSELTS 8
#elif defined(DCPLX)
   #define L1C_ELTS 2048L
   #define L1C_LSELTS 4
#endif

#define L2C_SZ 524288L
#define L2C_LS 64
#define L2C_NSET 1024
#define L2C_NWAY 8
#define L2C_INCLUSIVE 1
#define L2C_NSHARE 1
#define L2C_SURE 1
#ifdef SREAL
   #define L2C_ELTS 131072L
   #define L2C_LSELTS 16
#elif defined(DREAL) || defined(SCPLX)
   #define L2C_ELTS 65536L
   #define L2C_LSELTS 8
#elif defined(DCPLX)
   #define L2C_ELTS 32768L
   #define L2C_LSELTS 4
#endif

#define L3C_SZ 2097152L
#define L3C_LS 64
#define L3C_NSET 8192
#define L3C_NWAY 16
#define L3C_INCLUSIVE 0
#define L3C_NSHARE 4
#define L3C_SURE 1
#ifdef SREAL
   #define L3C_ELTS 524288L
   #define L3C_LSELTS 16
#elif defined(DREAL) || defined(SCPLX)
   #define L3C_ELTS 262144L
   #define L3C_LSELTS 8
#elif defined(DCPLX)
   #define L3C_ELTS 131072L
   #define L3C_LSELTS 4
#endif

#define LLPC_LVL 2
#define LLPC_SZ  L2C_SZ
#define LLPC_LSELTS L2C_LSELTS
#define LLC_LVL 3
#define LLC_LSELTS L3C_LSELTS
#define LLC_SZ 2129920L
#ifdef SREAL
   #define LLC_ELTS 655360L
#elif defined(DREAL) || defined(SCPLX)
   #define LLC_ELTS 327680L
#elif defined(DCPLX)
   #define LLC_ELTS 163840L
#endif

#define ATL_SAFELS 64

#define TLB_PLVLS 0
#define TLB_LVLS 0
#define TOTPTLB 0
#define TOTTLB 0

#endif /* done multiple inclusion guard */
