@INC TYPE
@TYPE SREAL
   @define pre  @s@
   @define upr  @s@
   @define type @float@
   @define typa @float@
   @define utyp @float@
   @define styp @float @
   @define stya @float @
   @define sadd @&@
   @define shift @@
   @define rzero @0.0f@
@TYPE DREAL
   @define pre  @d@
   @define upr  @d@
   @define type @double@
   @define typa @double@
   @define utyp @double@
   @define styp @double @
   @define stya @double@
   @define sadd @&@
   @define shift @@
   @define rzero @0.0@
@TYPE SCPLX
   @define pre  @c@
   @define upr  @s@
   @define type @void@
   @define typa @float@
   @define utyp @float@
   @define styp @void *@
   @define stya @float *@
   @define sadd @@
   @define shift @<<1@
   @define rzero @0.0f@
@TYPE DCPLX
   @define pre  @z@
   @define upr  @d@
   @define type @void@
   @define typa @double@
   @define utyp @double@
   @define styp @void *@
   @define stya @double *@
   @define sadd @@
   @define shift @<<1@
   @define rzero @0.0@
@TYPE !
