/* This file generated by /Users/whaley/TEST/ATLAS3.9.23.1/obj64/..//tune/blas/gemm/txover.c
*/
#ifndef ATL_TXOVER_H
#define ATL_TXOVER_H 1

#define ATL_PDIM 1
static const int ATL_tmmNN_SQmnk_XO[1] =
{166};
static const int ATL_tmmNT_SQmnk_XO[1] =
{166};
static const int ATL_tmmTN_SQmnk_XO[1] =
{166};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[9] =
{0,0,7596,2833,966,798,172,172,80};
static const int ATL_tmmNT_SmnLk_XO[9] =
{0,0,4308,2631,2631,690,187,172,80};
static const int ATL_tmmTN_SmnLk_XO[9] =
{0,0,0,3726,1331,446,187,172,80};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[9] =
{4885,4564,4210,2086,431,431,172,172,80};
static const int ATL_tmmNT_SmkLn_XO[9] =
{0,5169,1293,1077,1077,460,217,172,80};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[9] =
{0,0,0,0,850,294,172,172,80};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[9] =
{0,0,4680,3751,653,416,172,172,80};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[9] =
{273,273,214,200,200,171,171,171,80};
static const int ATL_tmmNT_SmLnk_XO[9] =
{330,330,330,258,199,185,171,171,80};
static const int ATL_tmmTN_SmLnk_XO[9] =
{472,416,416,316,244,200,171,171,80};
static const int ATL_tmmTT_SmLnk_XO[9] =
{389,389,389,375,244,185,171,171,80};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[9] =
{272,272,272,272,243,199,185,171,80};
static const int ATL_tmmNT_SnLmk_XO[9] =
{316,316,316,287,244,200,171,171,80};
static const int ATL_tmmTN_SnLmk_XO[9] =
{409,409,409,279,236,207,207,163,87};
static const int ATL_tmmTT_SnLmk_XO[9] =
{279,279,279,265,236,192,163,163,87};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[9] =
{323,205,191,177,163,163,163,163,87};
static const int ATL_tmmNT_SkLmn_XO[9] =
{310,310,191,177,177,177,177,163,87};
static const int ATL_tmmTN_SkLmn_XO[9] =
{338,338,220,191,191,191,177,163,87};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
