/* This file generated by /Users/whaley/TEST/ATLAS3.9.23.1/obj64/..//tune/blas/gemm/txover.c
 */
#ifndef ATL_TXOVER_H
   #define ATL_TXOVER_H 1

   #define ATL_PDIM 1
static const int ATL_tmmNN_SQmnk_XO[1] = 
   {107};
static const int ATL_tmmNT_SQmnk_XO[1] = 
   {99};
static const int ATL_tmmTN_SQmnk_XO[1] = 
   {99};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
 ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[9] = 
   {0,0,0,0,3658,367,310,48,48};
static const int ATL_tmmNT_SmnLk_XO[9] = 
   {0,0,0,0,1284,379,186,48,48};
static const int ATL_tmmTN_SmnLk_XO[9] = 
   {0,0,0,0,0,431,431,48,48};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
 ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[9] = 
   {3498,3498,3418,2408,655,299,175,48,48};
static const int ATL_tmmNT_SmkLn_XO[9] = 
   {5483,4820,3484,806,806,530,105,71,48};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
 ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[9] = 
   {0,0,0,3369,1450,754,99,65,48};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[9] = 
   {0,0,0,3399,633,276,152,48,48};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
 ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[9] = 
   {373,256,256,256,197,122,107,62,55};
static const int ATL_tmmNT_SmLnk_XO[9] = 
   {292,292,219,175,160,100,100,55,55};
static const int ATL_tmmTN_SmLnk_XO[9] = 
   {380,264,264,264,220,145,100,70,55};
static const int ATL_tmmTT_SmLnk_XO[9] = 
   {280,280,280,280,280,145,100,85,85};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
 ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[9] = 
   {262,203,189,189,175,161,146,70,63};
static const int ATL_tmmNT_SnLmk_XO[9] = 
   {160,160,160,160,160,100,100,78,63};
static const int ATL_tmmTN_SnLmk_XO[9] = 
   {285,285,285,227,152,137,107,62,55};
static const int ATL_tmmTT_SnLmk_XO[9] = 
   {190,190,190,190,190,115,115,70,70};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
 ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[9] = 
   {315,315,228,228,153,108,108,63,48};
static const int ATL_tmmNT_SkLmn_XO[9] = 
   {320,292,263,234,190,145,100,55,55};
static const int ATL_tmmTN_SkLmn_XO[9] = 
   {323,323,280,176,131,116,116,101,48};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
 ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
