/* This file generated by /Users/whaley/TEST/ATLAS3.9.23.1/obj64/..//tune/blas/gemm/txover.c
*/
#ifndef ATL_TXOVER_H
#define ATL_TXOVER_H 1

#define ATL_PDIM 1
static const int ATL_tmmNN_SQmnk_XO[1] =
{166};
static const int ATL_tmmNT_SQmnk_XO[1] =
{173};
static const int ATL_tmmTN_SQmnk_XO[1] =
{180};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[9] =
{0,0,0,0,7778,920,272,272,87};
static const int ATL_tmmNT_SmnLk_XO[9] =
{0,0,1913,1913,1913,754,754,255,102};
static const int ATL_tmmTN_SmnLk_XO[9] =
{0,0,0,0,7777,1633,243,243,89};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[9] =
{0,7651,6868,3090,2243,1291,433,262,108};
static const int ATL_tmmNT_SmkLn_XO[9] =
{0,0,0,4488,4488,2332,472,165,108};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[9] =
{0,0,0,0,7322,1435,864,185,108};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[9] =
{0,0,0,9004,5753,1234,472,165,108};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[9] =
{777,777,747,737,469,326,249,182,126};
static const int ATL_tmmNT_SmLnk_XO[9] =
{620,620,620,481,481,327,261,216,183};
static const int ATL_tmmTN_SmLnk_XO[9] =
{794,794,794,784,483,306,170,170,114};
static const int ATL_tmmTT_SmLnk_XO[9] =
{482,482,482,482,482,328,284,171,126};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[9] =
{481,481,481,481,481,327,250,171,126};
static const int ATL_tmmNT_SnLmk_XO[9] =
{605,605,605,605,605,329,307,160,149};
static const int ATL_tmmTN_SnLmk_XO[9] =
{666,666,666,666,494,473,249,170,114};
static const int ATL_tmmTT_SnLmk_XO[9] =
{818,726,726,696,504,327,250,194,149};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[9] =
{704,684,557,471,373,373,262,171,126};
static const int ATL_tmmNT_SkLmn_XO[9] =
{731,731,731,731,368,357,257,166,97};
static const int ATL_tmmTN_SkLmn_XO[9] =
{860,652,458,437,437,427,283,182,114};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
