/* This file generated by /Users/whaley/TEST/ATLAS3.9.23.1/obj64/..//tune/blas/gemm/txover.c
 */
#ifndef ATL_TXOVER_H
   #define ATL_TXOVER_H 1

   #define ATL_PDIM 1
static const int ATL_tmmNN_SQmnk_XO[1] = 
   {122};
static const int ATL_tmmNT_SQmnk_XO[1] = 
   {122};
static const int ATL_tmmTN_SQmnk_XO[1] = 
   {122};
#define ATL_tmmTT_SQmnk_XO ATL_tmmNN_SQmnk_XO
static const int *ATL_tmm_SQmnk_XO[4] =
{ATL_tmmNN_SQmnk_XO, ATL_tmmNT_SQmnk_XO,
 ATL_tmmTN_SQmnk_XO, ATL_tmmTT_SQmnk_XO};
static const int ATL_tmmNN_SmnLk_XO[9] = 
   {0,0,7296,5186,3383,3383,424,102,56};
static const int ATL_tmmNT_SmnLk_XO[9] = 
   {7070,5522,5522,5443,5443,209,209,102,56};
static const int ATL_tmmTN_SmnLk_XO[9] = 
   {0,0,0,0,8767,5360,574,142,56};
#define ATL_tmmTT_SmnLk_XO ATL_tmmNN_SmnLk_XO
static const int *ATL_tmm_SmnLk_XO[4] =
{ATL_tmmNN_SmnLk_XO, ATL_tmmNT_SmnLk_XO,
 ATL_tmmTN_SmnLk_XO, ATL_tmmTT_SmnLk_XO};
static const int ATL_tmmNN_SmkLn_XO[9] = 
   {6593,5157,4563,3309,3309,986,296,220,56};
static const int ATL_tmmNT_SmkLn_XO[9] = 
   {0,0,0,0,0,1698,780,74,65};
#define ATL_tmmTN_SmkLn_XO ATL_tmmNN_SmkLn_XO
#define ATL_tmmTT_SmkLn_XO ATL_tmmNT_SmkLn_XO
static const int *ATL_tmm_SmkLn_XO[4] =
{ATL_tmmNN_SmkLn_XO, ATL_tmmNT_SmkLn_XO,
 ATL_tmmTN_SmkLn_XO, ATL_tmmTT_SmkLn_XO};
static const int ATL_tmmNN_SnkLm_XO[9] = 
   {0,0,0,0,0,3513,234,79,56};
#define ATL_tmmNT_SnkLm_XO ATL_tmmNN_SnkLm_XO
static const int ATL_tmmTN_SnkLm_XO[9] = 
   {9741,7931,7454,5065,2656,1049,354,123,56};
#define ATL_tmmTT_SnkLm_XO ATL_tmmTN_SnkLm_XO
static const int *ATL_tmm_SnkLm_XO[4] =
{ATL_tmmNN_SnkLm_XO, ATL_tmmNT_SnkLm_XO,
 ATL_tmmTN_SnkLm_XO, ATL_tmmTT_SnkLm_XO};
static const int ATL_tmmNN_SmLnk_XO[9] = 
   {574,543,543,252,185,174,174,118,84};
static const int ATL_tmmNT_SmLnk_XO[9] = 
   {475,475,475,475,388,299,232,187,84};
static const int ATL_tmmTN_SmLnk_XO[9] = 
   {731,473,452,452,342,242,220,118,84};
static const int ATL_tmmTT_SmLnk_XO[9] = 
   {401,401,401,401,401,401,233,119,73};
static const int *ATL_tmm_SmLnk_XO[4] =
{ATL_tmmNN_SmLnk_XO, ATL_tmmNT_SmLnk_XO,
 ATL_tmmTN_SmLnk_XO, ATL_tmmTT_SmLnk_XO};
static const int ATL_tmmNN_SnLmk_XO[9] = 
   {352,352,352,352,352,352,159,102,79};
static const int ATL_tmmNT_SnLmk_XO[9] = 
   {586,586,586,586,586,402,234,96,73};
static const int ATL_tmmTN_SnLmk_XO[9] = 
   {666,666,666,484,237,237,158,101,90};
static const int ATL_tmmTT_SnLmk_XO[9] = 
   {619,588,567,536,493,328,238,113,67};
static const int *ATL_tmm_SnLmk_XO[4] =
{ATL_tmmNN_SnLmk_XO, ATL_tmmNT_SnLmk_XO,
 ATL_tmmTN_SnLmk_XO, ATL_tmmTT_SnLmk_XO};
static const int ATL_tmmNN_SkLmn_XO[9] = 
   {728,645,462,452,320,185,163,141,84};
static const int ATL_tmmNT_SkLmn_XO[9] = 
   {665,493,493,373,362,181,170,159,56};
static const int ATL_tmmTN_SkLmn_XO[9] = 
   {767,620,491,393,248,248,192,192,159};
#define ATL_tmmTT_SkLmn_XO ATL_tmmNN_SkLmn_XO
static const int *ATL_tmm_SkLmn_XO[4] =
{ATL_tmmNN_SkLmn_XO, ATL_tmmNT_SkLmn_XO,
 ATL_tmmTN_SkLmn_XO, ATL_tmmTT_SkLmn_XO};

#endif /* end ifndef ATL_TXOVER_H */
