.. -*- rst -*-
.. vim: ft=rst

.. This rst format file contains commonly used link targets
   and name substitutions.

.. NOTE: reST targets are
   __not_case_sensitive__

.. math-atlas
.. _math-atlas: http://math-atlas.sourceforge.net
.. _`math-atlas github`: http://github.com/rcwhaley/math-atlas
.. _`math-atlas mailing list`: http://sourceforge.net/mailarchive/forum.php?forum_name=math-atlas-devel
.. _`math-atlas home page`: http://math-atlas.sourceforge.net/
.. _`math-atlas home page`: http://math-atlas.sourceforge.net/
.. _`math-atlas developer home page`: http://math-atlas.sourceforge.net/devel/
.. _`atlas-contrib`: http://math-atlas.sourceforge.net/devel/atlas_contrib/
.. _`atlas-devel`: http://math-atlas.sourceforge.net/devel/atlas_devel/
.. _`atlas-docs`: http://math-atlas.sourceforge.net/faq.html#doc

.. git stuff
.. _git: http://git-scm.com/
.. _github: http://github.com
.. _github help: http://help.github.com
